QuesmaOrg/quesma

README.md
=> Add `goreportcard` badge

quesma/util/sql_pretty_fmt.go, quesma/util/sql_pretty_fmt_test.go
Make it look nicer, `WITH` broke it.
=> Pretty sql

quesma/queryparser/query_translator.go
I aim to unify json response generation. Currently, logic is split into many places. I started with simplifying logic building aggregation response tree.
=> Minor refactor query translator

quesma/model/query.go, quesma/model/select.go, quesma/optimize/trunc_date.go, quesma/queryparser/aggregation_parser.go, quesma/queryparser/query_util/query_util.go
I think CTEs should be pointers just like other nodes in the AST.
@trzysiek  please take a look
=> CTEs as pointers

quesma/model/base_visitor.go, quesma/model/highlighter.go, quesma/model/used_columns.go, quesma/optimize/trunc_date.go, quesma/plugins/elastic_clickhouse_fields/elastic_clickhouse_fields.go, quesma/queryparser/aggregation_parser.go, quesma/quesma/schema_array_transformer.go, quesma/quesma/schema_transformer.go, quesma/quesma/schema_transformer_test.go
We introduce a base visitor that implements the `model.ExprVisitor`.  We usually implement only one or two methods for the visitor. Other methods are the same. 
@pdelewski please take a look at this
=> Base model.Expr visitor 

quesma/quesma/recovery/recovery_strategies.go
Before this change, panics handled by `LogAndHandlePanic` were logged to the Quesma UI with only the stack trace - without any details about the error itself (for example without
`runtime error: comparing uncomparable type []string`). This made debugging panics harder.
This commit adds the error information from `commonRecovery` also to `LogAndHandlePanic`.
Before:
```
quesma request failed: panic recovered goroutine 3436 [running]:
runtime/debug.Stack() /Users/piotrgrabowski/sdk/go1.23rc1/src/runtime/debug/stack.go:26
+0x64 quesma/quesma/recovery.LogAndHandlePanic({0x1011f2510, 0x14004aaac90}
...
```
After:
<pre>
quesma request failed: Panic recovered: <b>runtime error: comparing uncomparable type []string</b>
goroutine 3027 [running]: runtime/debug.Stack() …
=> Print more error details in LogAndHandlePanic

quesma/clickhouse/clickhouse.go, quesma/clickhouse/clickhouse_test.go, quesma/clickhouse/insert_test.go, quesma/main.go, quesma/plugins/api.go, quesma/plugins/elastic_clickhouse_fields/elastic_clickhouse_fields.go, quesma/plugins/ingest_validator/ingest_validator.go, quesma/plugins/registry/plugin_registry.go, quesma/quesma/functionality/bulk/bulk.go, quesma/quesma/functionality/doc/doc.go, quesma/quesma/functionality/field_capabilities/field_caps.go, quesma/quesma/search.go
This PR:
- introduces required changes for ingest validation
- adds basic implementation of ingest validator
=> Handling ingest malformed fields - flow changes

smoke-test/main.go
It should be merged after #567
=> Smoke test - check if the table has valid columns 

bin/build-image.sh
=> Build image from all paths

quesma/clickhouse/quesma_communicator.go, quesma/eql/query_translator.go, quesma/model/query.go, quesma/queryparser/aggregation_parser_test.go, quesma/queryparser/query_parser.go, quesma/queryparser/query_parser_test.go, quesma/quesma/query_translator.go, quesma/quesma/search.go, quesma/quesma/search_opensearch_test.go, quesma/quesma/types/translated_sql.go, quesma/quesma/ui/live_tail.go, quesma/quesma/ui/live_tail_drilldown.go, quesma/quesma/ui/management_console.go, quesma/tracing/context.go
This PR adds the ability to execute an alternative execution plan in parallel. The results of the main and alternative plans are compared. 
There is no alternative plan enabled at this point.
=> Execution plan refactor 

.github/workflows/generate-notice.yml
This should make it excludable by CLA Assistant, it could not handle spaces
=> Use quesma-bot user for NOTICE.MD generation

quesma/clickhouse/parser.go
While testing Elastic Agent (Docker integration), I noticed that Quesma generated an invalid `CREATE TABLE` statement:
```
(...)
docker::cpu::core Tuple()
(...)
```
Having an empty Tuple is not allowed in ClickHouse. This type was inferred when receiving the following JSON field:
```
"core": {}
```
Fix the JsonToColumns function to ignore such a field instead of generating an empty Tuple column.
(Note that sometimes this field is non-empty, that's why Elastic Agent sent an empty one)
```
"core": {"pct":0.01963672211953173,"norm":{"pct":0.0012272951324707332}}
```
=> Fix JsonToColumns bug generating empty Tuple type

quesma/clickhouse/clickhouse.go, quesma/clickhouse/clickhouse_test.go, quesma/clickhouse/ingest_validator.go, quesma/clickhouse/ingest_validator_test.go, quesma/plugins/ingest_validator/ingest_validator.go, quesma/plugins/registry/plugin_registry.go
This PR adds validation to data ingest.
If a json field has a type that is different from db column, it will be added to attributes.
=> Adding ingest validation implementation

quesma/feature/not_supported.go
We have noticed that Quesma still has problems with properly idling (not making queries to ClickHouse Cloud to allow it to idle).
The current idling logic relies on checking if table discovery was recently used. It turns out that idle Kibana very often does inserts to an internal `.kibana` index and to `/_monitoring/bulk` endpoint.
Even though those requests are routed to Elastic, we still checked if `.kibana` or `_monitoring` are names of enabled indices using indexResolver - this use bumped the LastAccessTime, preventing idling.
Fix the issue by avoiding a use of indexResolver if it's an endpoint (`_endpoint`) or if it's an internal index (starting with `.`).
=> Fix spurious use of indexResolver preventing idling

.github/workflows/pipeline.yml
Cancel our tests in progress if new commit appears:
https://turso.tech/blog/simple-trick-to-save-environment-and-money-when-using-github-actions
=> Cancel PR checks on PRs when new commit appears

quesma/queryparser/pancake_aggregation_parser.go, quesma/queryparser/pancake_json_rendering.go, quesma/queryparser/pancake_model.go, quesma/queryparser/pancake_query_generation.go, quesma/queryparser/pancake_transformation.go, quesma/queryparser/pancake_transformation_test.go
Post merge pancake commits suggestions.
Centralize column name generation into one place.
=> Pancake column names

bin/ingest-clickhouse/Dockerfile, bin/ingest-clickhouse/README.md, bin/ingest-clickhouse/clickhouse.py, bin/ingest-clickhouse/drop_tables.py, bin/ingest-clickhouse/env.py, bin/ingest-clickhouse/full_insert_script.py, bin/ingest-clickhouse/normal_tables.py, bin/ingest-clickhouse/requirements.txt, bin/ingest-clickhouse/special_tables.py, bin/ingest-clickhouse/table.py, bin/ingest-clickhouse/table_data.py
Before running any of those scripts:
Insert script, and Clickhouse state after:
Drop tables script:
=> Script to download data from url and ingest to Clickhouse

quesma/clickhouse/clickhouse.go, quesma/quesma/ui/ingest.go, quesma/stats/ingest_statistics.go
Basic ui for schema non-compliant fields
=> Ui report for ingest schema non-compliant fields

quesma/model/typical_queries/hits.go
Before this change, the fields of array type were not rendered correctly in `hits`. For example, in the "Discover" tab for "Kibana Sample Data eCommerce", the JSON representation of "manufacturer" looked like:
```
"manufacturer": [
[
"Elitelligence",
"Oceanavigations"
]
],
```
instead of:
```
"manufacturer": [
"Elitelligence",
"Oceanavigations"
],
```
This could cause some arrays to display incorrectly in the Kibana UI.
The cause of the problem was that we always wrapped column values into 1-element array, even if the value was an array itself. Fix the issue by handling array values differently.
=> Fix rendering of fields of array type in `hits`

quesma/clickhouse/clickhouse.go, quesma/clickhouse/clickhouse_test.go, quesma/clickhouse/parser.go, quesma/clickhouse/table.go
This PR removes others as it is redundant to attributes (and maybe map in the future)
=> Removing others column

quesma/queryparser/pancake_aggregation_parser.go, quesma/queryparser/pancake_transformer.go, quesma/queryparser/pancake_transformer_test.go
Pancakes depend on unique names. The code needs to deal with edge cases well.
=> Pancakes column names

quesma/quesma/router.go
This caught my attention while working on sth else, but quick search and replace and the code's a little cleaner :)
=> Use HTTP Status codes from `http` package

quesma/queryparser/pancake_aggregation_parser_buckets.go, quesma/queryparser/pancake_sql_query_generation.go, quesma/queryparser/pancake_sql_query_generation_test.go, quesma/testdata/kibana-visualize/aggregation_requests.go
old: There's one hack in the changes. Let's wait for #635 merge and then it might get fixed, not sure.
new: Yeah, some previous fixes made this PR very straightforward. Not much to comment on.
=> Pancake `multi_terms` aggr

quesma/clickhouse/clickhouse.go, quesma/clickhouse/clickhouse_test.go
This PR introduces few changes to clarify and cleanup build ingest sql statements workflow
=> Build insert improvements

quesma/clickhouse/alter_table_test.go, quesma/clickhouse/clickhouse.go, quesma/clickhouse/clickhouse_test.go, quesma/clickhouse/insert_test.go
This PR: 
- enables altering column mechanism as default
- introduce simple heuristic (first N columns is added by default, next columns are added based on simple statistic calculation)
- opens a way for changing/extending current heuristic
=> Alter column heuristic

quesma/quesma/schema_transformer.go, quesma/quesma/schema_transformer_test.go
Tests for transformations added here: https://github.com/QuesmaOrg/quesma/pull/672 and https://github.com/QuesmaOrg/quesma/pull/676
CC @pdelewski
=> Pipeline transformers - missing tests

quesma/clickhouse/clickhouse.go, quesma/clickhouse/ingest_validator_test.go
As discussed we would like to version attributes metadata values
=> Adding attributes metadata version prefix

quesma/quesma/functionality/terms_enum/terms_enum_test.go
https://github.com/QuesmaOrg/quesma/pull/693
Simple test checking if aliases are taken into consideration.
=> Add test for #693

quesma/model/pipeline_aggregations/average_bucket.go, quesma/model/pipeline_aggregations/bucket_script.go, quesma/model/pipeline_aggregations/cumulative_sum.go, quesma/model/pipeline_aggregations/derivative.go, quesma/model/pipeline_aggregations/max_bucket.go, quesma/model/pipeline_aggregations/min_bucket.go, quesma/model/pipeline_aggregations/serial_diff.go, quesma/model/pipeline_aggregations/sum_bucket.go, quesma/model/pipeline_query_type.go, quesma/model/query.go, quesma/queryparser/pancake_pipelines.go, quesma/queryparser/pancake_transformer.go, quesma/quesma/search_alternative.go
Unify aggregation type as it simplifies the code base.
=> Unify aggregation types

quesma/quesma/config/config.go, quesma/quesma/config/config_v2.go
Adding handy option to disable telemetry collection.
=> Telemetry disabling option

quesma/clickhouse/clickhouse.go, quesma/clickhouse/parser.go
Moving some things around to build proper ingest workflow with goal to have fields encoding in one function
=> nested fields encoding, #3

quesma/ab_testing/collector/collector.go, quesma/ab_testing/sender/coordinator.go
A/B testing starts without any delay now.  The delay caused an 'it doesn't work' experience for fast devs.
=> A/B testing - start ASAP

adr/5_nested_fields_representation.md
This adr contains list of all considered solutions for nested fields encoding over time. 
It still may be incomplete regarding all pros and cons.
=> Adding adr for nested fields representation

quesma/clickhouse/clickhouse.go
This PR does two things:
- Encodes fields in exactly one place.
- Makes processInsertQuery more pure by postponing all query execution calls to a single location.
=> Do field encoding once at the beginning

quesma/model/bucket_aggregations/geotile_grid.go, quesma/model/metrics_aggregations/geo_cetroid.go, quesma/queryparser/pancake_aggregation_parser_buckets.go, quesma/quesma/schema_transformer.go
=> Geo in pancakes

quesma/quesma/config/config_v2.go
In the `config_v2.go` we support a single pipeline use-case. The code permitted having a single pipeline for querying with processor: either `QuesmaV1ProcessorNoOp` or `QuesmaV1ProcessorQuery`. This commit fixes two things about it:
1. This validation is misleading - the user requested Quesma with only querying enabled, but actually ingest got also enabled. Therefore this commit will now reject query-only pipelines.
2. `if proc.Type == QuesmaV1ProcessorQuery` was incorrectly nested (it was inside `if proc.Type == QuesmaV1ProcessorQuery`), therefore the code was actually never executed.
=>  Fix validation of single pipeline case

quesma/quesma/config/config_v2.go
This commit adds additional validation of backend connectors. The existing implementation, such as methods like `getRelationalDBBackendConnector()` essentially assumes that there's only 1 ClickHouse connector. If the user defines many ClickHouse connectors, the implementation will silently use only the first one. Fix that problem by forbidding specifying many CH backend connectors and ES backend connectors. In the future we might relax that requirement.
Additionally, `TranslateToLegacyConfig` is refactored to use the same "`isSinglePipeline`, `isDualPipeline`" logic as `validatePipelines()`.
=> Refactors, additional backend validation in config_v2.go

quesma/ab_testing/collector/collector.go, quesma/ab_testing/collector/diff.go, quesma/ab_testing/collector/fanout.go, quesma/ab_testing/collector/filters.go, quesma/ab_testing/collector/processors.go, quesma/quesma/search_alternative.go
This PR adds some improvements:
1) better error handling 
2) override elastic endpoint setting 
We should configure A/B testings using backend connectors. It'll be done later.
=> A/B testing - some improvements

quesma/model/bucket_aggregations/multi_terms.go, quesma/model/bucket_aggregations/terms.go, quesma/model/query_result.go, quesma/testdata/aggregation_requests.go
Just a small removal of some pre-pancake code (+ fix expected results for 1 test)
=> Very small code cleanup

quesma/clickhouse/table_discovery.go, quesma/common_table/const.go, quesma/ingest/alter_table_test.go, quesma/ingest/insert_test.go, quesma/ingest/parser.go, quesma/ingest/processor.go, quesma/ingest/processor_test.go, quesma/model/query_result.go, quesma/model/typical_queries/hits.go, quesma/quesma/schema_transformer.go
This PR fixes:
1. Add column comments while altering the tables. 
2. Returns valid `_index` value for each row.
=> Common table - fixes 

quesma/ingest/insert_test.go, quesma/ingest/parser.go
=> Fix missing a metadata comment

quesma/ab_testing/sender/coordinator.go, quesma/clickhouse/connection.go, quesma/connectors/connector.go, quesma/main.go, quesma/quesma/config/config.go, quesma/quesma/config/config_v2.go, quesma/quesma/search.go, quesma/quesma/search_alternative.go
My trial run found several DX issues and addressed them
- we inspect packages in transparent proxy and write weird errors when JSON or NJSON is here
- disabled for now
- we show ClickHouse DB error
- don't do try on moc error
- in fact remove `mock-for-transparent-proxy` as this is confusing
- A/B logs are there even if there is no test
- do detection on that
Along the way added constant and removed some dead code.
=> Transparent proxy fixes

bin/build-image.sh
@mieciu said it should be changed
=> Quickfix build-image

quesma/model/query_result.go, quesma/queryparser/aggregation_parser_new_logic_test.go, quesma/queryparser/pancake_json_rendering.go, quesma/queryparser/pancake_sql_query_generation_test.go, quesma/queryparser/query_translator.go, quesma/quesma/search_test.go, quesma/util/utils.go, quesma/util/utils_test.go
=> Remove unused relic `model.KeyAddedByQuesma`

quesma/model/metrics_aggregations/common.go, quesma/model/pipeline_aggregations/sum_bucket.go, quesma/queryparser/aggregation_parser_test.go, quesma/queryparser/pancake_sql_query_generation_test.go, quesma/testdata/kibana-visualize/pipeline_aggregation_requests.go, quesma/testdata/opensearch-visualize/aggregation_requests.go
3 tests that I were able to click out in Kibana + small fix to `sum_bucket`, it works with dates now
=> Tests for #847

quesma/elasticsearch/client.go, quesma/elasticsearch/index_resolver.go, quesma/elasticsearch/requests.go, quesma/health/elastic.go, quesma/persistence/elastic.go, quesma/quesma/search_alternative.go, quesma/telemetry/phone_home.go
We didn't add auth in all places where it's needed.
Moved adding auth to one place.
Before (Hdx with `3` config), even though Elastic is working:
Then restart:
After:
=> Sign ui healthcheck

quesma/quesma/async_search_storage/in_memory.go, quesma/quesma/search.go
Just style:
* change some internal struct to small letter to not pollute global symbols
* merge error and no-error flow into one.
=> [v. small] Persistent storage for asyncs 2

quesma/elasticsearch/index_management.go, quesma/elasticsearch/index_resolver.go, quesma/main.go, quesma/quesma/functionality/resolve/resolve.go, quesma/table_resolver/rules.go, quesma/table_resolver/table_resolver.go
This PR fixes some regressions with elastic fallback in security mode.
before:
after:
=> Fixing elastic fallback in security mode

quesma/quesma/ui/login.go
=> UX - focus username field on page load 

quesma/queryparser/pancake_json_rendering.go
Only few very minor changes need to still be ported from https://github.com/QuesmaOrg/quesma/pull/867
It's first of them.
=> Minor fixes to query response renderer

quesma/quesma/ui/console_routes.go, quesma/quesma/ui/es_auth_provider.go, quesma/quesma/ui/html_utils.go, quesma/quesma/ui/login.go
@mieciu please test it before merging. I could not do that locally.
It fixes two issues:
- right redirect if you host it on different domain than localhost
- do also redirect if HTMX hit it in some fragment (auto-refreshed panel)
=> Improve login redirect

quesma/quesma/config/config_v2.go, quesma/quesma/config/config_v2_test.go, quesma/quesma/config/test_configs/has_common_table.yaml
I have to revert it temporarily as integration tests failing https://github.com/QuesmaOrg/quesma/actions/runs/11719484324/job/32643244756
=> Revert UseCommonTable global flag

quesma/quesma/search_ab_testing.go
It fixes A/B testing sync searches.
=> A/B - fix sync search 

quesma/queryparser/query_parser.go, quesma/quesma/config/config.go, quesma/testdata/requests.go
https://github.com/QuesmaOrg/quesma/pull/949 fixed size parsing for aggregations, but it can as well appear in top-level query part.
=> Fix size parsing

quesma/quesma/schema_array_transformer.go
It fixes "[Logs] Web Traffic" dashboard panel:
Before: 
After:
=> Fix using '=' operator  against an array

quesma/quesma/http_headers.go, quesma/quesma/http_headers_test.go
Closes: https://github.com/QuesmaOrg/quesma/issues/994
=> Change `Content-Type` header to be Kibana 7 compatible

quesma/quesma/ui/console_routes.go
This should be added here #1031. Sorry
=> Add another pprof endpoint

quesma/painful/model.go, quesma/painful/model_test.go
Actually, the data format could be different too. Fix it and add it to test.
=> Minor painless fix

quesma/painful/model.go
Not sure if it's final, but that's where I end up today.
=> Another last minute fix

quesma/processors/es_to_ch_ingest/elasticsearch_to_clickhouse_ingest_processor.go
Due to: https://github.com/QuesmaOrg/quesma/pull/1081
=> Update new ingest processor to the new router

bin/it.sh, bin/ut.sh
A simple short-hand instead of my bashrc. Others might find this useful.
=> Add scripts to run unit and integration tests.

quesma/frontend_connectors/elastic_http_frontend_connector.go, quesma/main.go
This PR removes some redundant code already handled by embedded struct
=> v2 - Removing redundant dependency injection code 

quesma/main.go, quesma/v2/core/quesma_builder.go
This PR fixes problem mentioned in the title. It's not generic solution yet, however it good enough for now. I plan to work on generic solution in next PR
=> Fixing bind: address already in use

quesma/main.go, quesma/main_test.go, quesma/v2/core/quesma_builder.go
This PR generalizes some aspects of `quesma build()` implementation and adds few unit tests.
=> Generalizing quesma build implementation

quesma/clickhouse/table_discovery.go
FYSA @nablaone, this will still work like https://github.com/QuesmaOrg/quesma/pull/1169/files but with less lines.
Unfortunately this slipped unnoticed when working on that larger PR of mine when I wasn't sure if `QueryRow` will become part of the backend connector API.
=> Use `QueryRow` whenever applicable in `table_discovery.go`

quesma/schema/registry.go
This reverts commit f8bce5dc8c237fa847eb86f58d781226d2a78adc.
=> Revert "Schema cache  (#1165)"

quesma/clickhouse/table_discovery.go
Tiny fix to fetching create table query.
=> [HOTFIX] Fix row iteration

quesma/frontend_connectors/elasticsearch_ingest.go, quesma/frontend_connectors/elasticsearch_query.go, quesma/frontend_connectors/router_v2.go, quesma/ingest/processor.go, quesma/ingest/processor_test.go, quesma/main.go, quesma/main_test.go, quesma/processors/es_to_ch_common/common.go, quesma/processors/es_to_ch_ingest/elasticsearch_to_clickhouse_ingest_processor.go, quesma/processors/es_to_ch_query/elasticsearch_to_clickhouse_query_processor.go, quesma/quesma/config/config_v2.go, quesma/quesma/functionality/bulk/bulk.go, quesma/quesma/schema_transformer.go, quesma/table_resolver/table_resolver_dummy.go, quesma/v2/core/mux.go, quesma/v2_quesma_builder.go
https://github.com/QuesmaOrg/quesma/pull/1178 has just scratched the surface and was mostly about bridging the gap between v1 and v2 API. 
This PR is a continuation on v2 ingest processor. Fixing routing, doubled dependencies and many more.
=> Further work on Ingest Processor v2

quesma/elasticsearch/healthchecker.go, quesma/quesma/ui/dashboard.go, quesma/quesma/ui/dashboard_healthcheck.go, quesma/telemetry/phone_home.go, quesma/v2/core/health.go
Distributing content of health package to more appropriate existing packages
=> Moving health package content

ci/it/testcases/test_ab.go
https://github.com/QuesmaOrg/quesma/pull/1205/files changed the behavior of AB testing sender
=> Temporarily sunset A/B integration test

quesma/quesma/ui/ab_testing.go
This  PR brings the A/B console back to life.
=> Fix A/B testing console

.github/workflows/build-quesma-docker-image.yml, .github/workflows/e2e-tests.yml, .github/workflows/generate-notice.yml, .github/workflows/integration-tests.yml, .github/workflows/pipeline.yml, .github/workflows/release.yml, README.md, ci/e2e-data-generator/go.mod, ci/it/go.mod, quesma/go.mod, quesma/model/expr_string_renderer.go, quesma/queryparser/pancake_aggregation_parser.go, smoke-test/go.mod
Bump go lang version and fix two issues along the way.
=> Upgrade to go version 1.24

quesma/go.mod, quesma/go.sum, quesma/quesma/ui/console_routes.go, quesma/telemetry/phone_home.go, quesma/telemetry/prometheus_metrics.go
Add a few basic Prometheus-style metrics. Easy to add more when you need them.
=> Implement Promethous metric endpoint

quesma/frontend_connectors/dispatcher.go
Everything at `debug` level of course...
=> Help examine `Error reading request body: unexpected EOF, url=/_bulk`

bin/build-image.sh
Stopped working after `quesma -> platform` name change
=> `build-image.sh` quickfix

platform/ingest/parser.go
Some map panels work better now.
=> [`sample_ecommerce`] Keep geo in Clickhouse as floats, not strings

ci/it/testcases/test_ingest.go, ci/it/testcases/test_table_override.go
=> Make ITs pass

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/integration-tests.yml
We could just comment with
>/run-integration-tests
and have the IT run
=> Run ITs on GitHub PR comment

.github/workflows/integration-tests.yml
=> Update PR status when IT run was requested for PR

.github/workflows/integration-tests.yml
=> Allow IT job to update PR status

.github/workflows/integration-tests.yml
=> Fix PR status update

platform/main.go
Add panic recovery to the main config.
Verified that this works by manually adding panic.
=> Add panic recovery in main

ci/e2e.yml
=> Fixing e2e

.github/workflows/build-quesma-docker-image.yml, .github/workflows/release.yml, .gitignore, Dockerfile, bin/build-image.sh, ci/ci.yml, cmd/go.mod, platform/ingest/processor.go
=> Take local platform dependency

platform/clickhouse/table_discovery.go, platform/config/index_config.go
This PR fixes the addition of a map field to the schema in case of subsequent query failures and adds more logging.
=> Map fields discovery fix, additional logging

platform/clickhouse/table_discovery.go
We could get a lot of duplicates
=> Field caps for maps : get rid of key duplications

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/integration-tests.yml
The lazy of the world, unite! 😉 
Talked to @mieciu, the author, and he didn't mind.
=> Alias `/run-it -> /run-integration-tests`

cmd/experimental/go.mod, cmd/experimental/go.sum
Forgot `experimental/` directory in here https://github.com/QuesmaOrg/quesma/pull/1301
Can merge, don't look - this package is only used in pretty sql printer anyway.
=> [tiny] Update 1 package also in `experimental/`

platform/frontend_connectors/schema_transformer.go, platform/frontend_connectors/schema_transformer_test.go, platform/parsers/elastic_query_dsl/query_parser.go
=> Fix broken `_id`s

platform/frontend_connectors/schema_array_transformer.go
This PR is about lowering sanity check log message level to warning.
=> Changing this sanity check from error to warning

platform/clickhouse/clickhouse.go, platform/clickhouse/table.go, platform/clickhouse/table_discovery.go, platform/frontend_connectors/schema_transformer.go, platform/frontend_connectors/schema_transformer_test.go
This PR is about supporting `FROM cluster(<name>, <table>)`
=> Support for cluster function as table expression

platform/parsers/sql/parser/core/node.go, platform/parsers/sql/parser/main.go, platform/parsers/sql/parser/pipe_syntax/cte_transpiler.go, platform/parsers/sql/parser/transforms/visitors.go
This PR adds an alternative transpiler. This transpiler outputs SQL as a CTE query. There is also some improvement regarding space handling. 
It's experimental code.
@avelanarius  Please take a look at it. I don't know if everything is handled well.
=> Transpile to CTE 

.github/workflows/integration-tests.yml, .github/workflows/issues-and-prs-yml
=> Send slack message on new issue

platform/ingest/parser.go
This is follow up to https://github.com/QuesmaOrg/quesma/pull/976
=> Array mapping parser improvements

.github/workflows/integration-tests.yml
I hope this will fix that, although we have to merge it to check if this really works.
=> Fix `main` branch IT triggeting params

platform/ui/console_routes.go
Fix two issues:
- We want to expose goroutine stack traces endpoint too
- Protect pprof using authentication to prevent security issues
=> Pprof endpoint

ci/it/testcases/utils.go
=> Log docker image used for integration tests

bin/ingest-clickhouse/requirements.txt
=> Fixes for FOSSA v1
