QuesmaOrg/quesma

quesma/quesma/search_norace_test.go, quesma/quesma/static_registry_test.go
We exclude some tests when we run race which leads to compilation failure. This is present only on main, but not in PR.
=> Move static registry to new file

quesma/queryparser/query_parser.go, quesma/testdata/requests.go
Simple error, we translated `must_not (a && b)` into `NOT a OR NOT b` which of course isn't correct. Changed it to `not (a or b)`.
Before (we should have 0 results as all `@timestamp`s fall into second `range`):
After:
Proof that it's indeed not a AND not b in Elastic: with one condition, we have >0 results, with 2 we have none, so it can't be OR like we used to have.
=> Quickfix: `must_not` generated incorrect SQL

quesma/quesma/functionality/terms_enum/terms_enum.go, quesma/quesma/search.go, quesma/quesma/ui/asset/head.html, quesma/quesma/ui/html_pages_test.go, quesma/quesma/ui/live_tail.go, quesma/quesma/ui/live_tail_drilldown.go, quesma/quesma/ui/management_console.go
After this change each SQL query in the "Translated SQL" view on Live Tail Drilldown page is now clickable and routes to the ClickHouse `/play` webpage with the query pre-filled-in, which makes it very convenient to quickly run and modify it.
This change required changing the way query bodies are stored internally - previously the queries were concatenated to a single large blob, but now each query is stored separately (as a `[]byte`), making it possible to display them separately in the UI.
=> Make SQL queries clickable in Live Tail Drilldown

.github/workflows/release.yml
Adding more build args and new image location (Docker Hub)
=> Docker Hub builds

.github/workflows/release.yml
A tiny fix to `release.yml`. 
I've thought that default input values are going to be used, but apparently that's not the case and for jobs triggered by a push to branch `github.event.inputs` is empty 
Ref: https://github.com/orgs/community/discussions/26322
=> Hotfix `release.yml`

quesma/clickhouse/table.go, quesma/model/bucket_aggregations/date_histogram.go, quesma/model/bucket_aggregations/date_histogram_test.go, quesma/model/expr.go, quesma/model/query.go, quesma/queryparser/aggregation_parser.go, quesma/queryparser/aggregation_parser_test.go, quesma/queryparser/query_parser.go, quesma/queryparser/query_translator.go, quesma/testdata/aggregation_requests.go, quesma/testdata/aggregation_requests_2.go
I'll quickfix that:
Also while at it, `calendar_interval` and `fixed_interval` have different sematic (slightly, but it can very easily be reproduced making our responses incorrect). `Date histograms` are very very common, so it'd be good to have it correct, it's not much work.
=> Fix graying `date_histogram`

quesma/quesma/quesma.go
In commit 9b9be28602 `peekBody` was extended to handle compressed requests by decompressing them.
This worked well in case of Quesma handling the request on its own (sending to ClickHouse). However, if Quesma decides to route the query to ElasticSearch ("transparent proxy case") it will attempt to send the uncompressed body with the original headers, which includes `Content-Encoding: gzip` header. The receiver (Elastic) then errored out trying to decompress an uncompressed body.
Fix the problem by removing the `Content-Encoding` header after decompression.
I manually tested the code with Filebeat: compressed/uncompressed traffic to both Elastic via Quesma and to ClickHouse via Quesma. Previously the compressed traffic to Elastic via Quesma would error out, but this change solves it. …
=> Fix handling of gzip-compressed requests in transparent proxy case 

quesma/queryparser/query_translator.go, quesma/quesma/matchers.go, quesma/quesma/router.go, quesma/quesma/search.go, quesma/quesma/ui/dashboard.go, quesma/quesma/ui/live_tail_drilldown.go, quesma/quesma/ui/management_console.go, quesma/testdata/aggregation_requests.go, quesma/testdata/facets_requests.go, quesma/tracing/async_trace_logger_test.go, quesma/tracing/context.go
@avelanarius requested change, be able to search by `quesma_async_...`. Now you can check the dashboard ID of the response and then find a matching one in Quesma.
While there, I added two minor styles, one in the dashboard and the other in total time.
=> Minor UI fixes

quesma/queryparser/query_translator.go
Another stepping stone toward unifying rendering json:
- Make JSON rendering step more consistent, stop at the same level
- the logic is much shorter
- do not pass array with one element
@trzysiek should review
=> Simplify json rendering refactor

quesma/queryparser/lucene/expression.go, quesma/queryparser/lucene/lucene_parser.go, quesma/queryparser/lucene/lucene_parser_test.go, quesma/queryparser/query_parser.go
Lucene query parser needs to be able to substitute field names with their internal representation
=> Resolve internal property names for columns references in lucene queries

examples/kibana-sample-data/quesma/config/local-dev.yaml, http_requests/field_caps.http, quesma/plugins/elastic_clickhouse_fields/elastic_clickhouse_fields.go, quesma/plugins/registry/plugin_registry.go, quesma/queryparser/query_parser.go, quesma/schema/registry.go
Double colons are our internal implementation detail - described [here](https://github.com/QuesmaOrg/quesma/blob/399fd231bb97437687bc18b88a734939fe47357e/adr/4_double_colon_as_nested_structure_separator.md). Users should not know about it, but use classic dots as separators.
depends on:
- https://github.com/QuesmaOrg/quesma/pull/526
- https://github.com/QuesmaOrg/quesma/pull/525
- https://github.com/QuesmaOrg/quesma/pull/527
=> Don't expose internal '::' separators to clients

quesma/clickhouse/quesma_communicator.go, quesma/model/query.go, quesma/optimize/cache_group_by.go, quesma/optimize/pipeline.go, quesma/optimize/pipeline_test.go, quesma/optimize/trunc_date.go, quesma/queryparser/query_translator.go, quesma/quesma/quesma.go, quesma/quesma/search.go
Let's introduce the SQL query optimization pipeline.
Now there are only two optimizations supported: 
- truncate dates to 5 minutes, it  will limit how many distinct queries we perform
- cache aggregation queries ("GROUP BY"), these queries can be slow, and produce a low number of rows, 
Optimizations are disabled for tests. 
Currently,  performed optimizations are not visible in the "Live View" tab. I will add it in the next PR.
=> Add optimization pipeline

quesma/quesma/functionality/resolve/resolve.go, quesma/quesma/functionality/resolve/resolve_test.go, quesma/quesma/router.go, quesma/schema/registry.go, quesma/schema/registry_test.go, quesma/schema/schema.go, quesma/schema/schema_test.go
Before this change, the `_resolve` endpoint had several bugs. One of them, which affected me, was wrong result for an index present in Elastic, but missing from ClickHouse and not enabled in the config. In that case Quesma should reach to Elastic, but previously it just looked at ClickHouse and immediately returned 404.
Since the previous logic was quite convoluted and used older `LogManager` instead of `schema.Registry`, this PR largely rewrites the implementation to be simpler, better documented and to use the `schema.Registry`.
I extensively tested all possible scenarios (see the table in `Test_combineSourcesFromElasticWithRegistry`), both as a unit test and manually in Kibana. 
The resolve code is now also moved to `functionality/resolve` package.
To make it possible to use the …
=> Rewrite _resolve endpoint to use the schema registry

quesma/clickhouse/quesma_communicator.go, quesma/model/query.go, quesma/quesma/functionality/terms_enum/terms_enum.go, quesma/quesma/schema_transformer.go, quesma/quesma/search.go, quesma/quesma/types/translated_sql.go, quesma/quesma/ui/html_pages_test.go, quesma/quesma/ui/live_tail.go, quesma/quesma/ui/live_tail_drilldown.go, quesma/quesma/ui/management_console.go
In the "Live View" tab we display additional information for each executed SQL query: 
- duration time
- which schema transformation was applied
- which optimizations were performed
=> Live view - show query time and transformations

quesma/clickhouse/schema_loader.go, quesma/clickhouse/schema_management.go, quesma/quesma/config/index_config.go
Adding table auto discovery logic. It's pretty basic for now, but should elevate customer experience when they first set up Quesma.
Auto-discovery kicks in whenever `indexes` section in configuration is left empty. Additionally to tables, we try to detect a "timestamp field" via simple heuristics.
=> Table autodiscovery

quesma/clickhouse/clickhouse.go, quesma/clickhouse/clickhouse_test.go, quesma/clickhouse/insert_test.go, quesma/clickhouse/parser.go, quesma/connectors/connector.go, quesma/main.go, quesma/plugins/elastic_clickhouse_fields/elastic_clickhouse_fields.go, quesma/queryparser/aggregation_parser_test.go, quesma/queryparser/query_parser_test.go, quesma/quesma/functionality/field_capabilities/field_caps_test.go, quesma/quesma/functionality/terms_enum/terms_enum_test.go, quesma/quesma/highlight_test.go, quesma/quesma/static_registry_test.go
When ingesting data into ClickHouse via Quesma, the first insert can automatically create a corresponding table in ClickHouse (if a user didn't do it beforehand).
That CREATE TABLE statement was previously based solely on the contents of the first inserted data (the first JSON). However, the information in that first JSON is often not sufficient to create a good ClickHouse schema. Prior to this change, the only way for the user to affect the CREATE TABLE was to perform it manually beforehand.
Extend the CREATE TABLE generation code to also take into account the information in schema the registry. Therefore the user can have some control over the CREATE TABLE statement via the "mapping" configuration in the config file. In practice this allows for:
1. Overriding the type of column (for …
=> Use schema registry information in CREATE TABLE

quesma/quesma/config/config.go, quesma/quesma/config/index_mappings.go, quesma/quesma/functionality/bulk/bulk.go, quesma/quesma/index-mapping-query-rewriter.go, quesma/quesma/index_mapping_query_rewriter.go, quesma/quesma/index_mapping_query_rewriter_test.go, quesma/quesma/schema_transformer.go, quesma/quesma/search.go
This PR adds new configuration settings to map input/source indexes to internal database table (that's proposal, I'm open to suggestions)
```
indexMappings:
big_kibana_common_table:
sourceIndexes: ["kibana_sample_data_flights", "kibana_sample_data_logs"]
```
It then uses this information to rewrite all table references to specified common database table. Rewriting table references in from clause should be sufficient for our current needs
=> POC N index -> 1 table mapping

quesma/clickhouse/clickhouse.go, quesma/clickhouse/schema_loader.go
Quesma 1 minute schema refresh prevents taking advantage of DB idling. This PR fixed that by:
- stops periodic refresh if there is no-one uses schema (no queries)
- force refresh after long idle time
Unfortunately this logic is tricky to unit test.
CC @avelanarius
=> Make reloading happen only if people access the Quesma

quesma/elasticsearch/index_management.go
Fix a nil pointer dereference in `GetSourceNames()`, which happened quite often for me while developing Quesma - I often start Quesma before Elastic is fully up, therefore `im.sources` would be nil (failed to load from Elastic) and `GetSourceNames()` would panic.
=> Fix a nil pointer dereference in GetSourceNames()

quesma/clickhouse/quesma_communicator.go, quesma/optimize/cache_group_by.go, quesma/optimize/materialized_view_replace.go, quesma/optimize/pipeline.go, quesma/optimize/pipeline_test.go, quesma/optimize/trunc_date.go, quesma/quesma/config/config.go, quesma/quesma/config/index_config.go
This PR adds an optimizer that rewrites queries and replaces the original table with a materialized view.  The rewrite rule is taken from the configuration. 
Suppose we've got the following table:
```
CREATE some_index (
`date` DateTime64(3),
`type` String,
... 
)
ENGINE=MergeTree()
ORDER BY (`date`)
```
We've discovered our dashboard generates a lot of queries with common expressions:
```
(type ILIKE '%foo%')
```
We may create a materialized view and query it instead of the original table.
Notice that the materialized view is updated on INSERT, it must be created before ingest.
```
-- a table that holds materialized view data 
CREATE table some_index_foo_dest (
`date` DateTime64(3),
`type` String,
... 
)
-- an index 
CREATE MATERIALIZED VIEW some_index_foo_mv to some_index_foo_dest AS …
```
=> Optimizer - Rewrite query using a materialized view 

quesma/clickhouse/connection.go, quesma/config.yaml.template, quesma/quesma/config/config.go
So we have this logic to ignore creating TLS-based connections when we get specific TLS-related errors (assuming that plaintext connection should be used).
However, when we start Quesma while ClickHouse is dead, aforementioned logic doesn't work and we don't fallback to non-TLS connection properly, as the error is just "connection refused":
So eventually when plaintext ClickHouse comes up, the pool will keep failing repeatedly with `tls: first record does not look like a TLS handshake`.
The proposed remediation is to just allow explicitly disabling TLS via configuration.
**Alternative approach** would be to derive this property by looking at port numbers: 
* 9000 -> no TLS
* 9440 -> TLS
of course being very verbose in logs about Quesma's choice.
=> Allow disabling TLS explicitly

quesma/clickhouse/clickhouse.go
This have slipped unnoticed. 
If only one out of few license check calls fails (e.g. db being temporarily unavailable), `returnedErr` was not reset and shadowed the passing check.
This PR updates this logic - a single passed check resets `returnedErr` and immediately returns, additionally cancelling further (unnecessary) executions.
=> Fix license check when DB conn is flapping

quesma/telemetry/duration.go, quesma/telemetry/duration_test.go, quesma/telemetry/empty.go, quesma/telemetry/multi_counter.go, quesma/telemetry/multi_counter_test.go, quesma/telemetry/phone_home.go
Two changes:
- allow ClickHouse to enter idle by not querying it during phone home when there is no traffic
- reset counters after each phone home (every hour)
CC @nablaone
=> Phone home change

quesma/eql/query_translator.go, quesma/model/typical_queries/hits.go, quesma/queryparser/query_parser.go, quesma/queryparser/query_translator.go, quesma/queryparser/query_translator_test.go, quesma/quesma/functionality/field_capabilities/field_caps.go, quesma/quesma/index_mapping_query_rewriter.go, quesma/quesma/query_translator.go, quesma/quesma/search.go
This PR implements some missing pieces to connect index <-> tables mappings e2e like field caps.
According configuration all request for `kibana_sample_data_flights` go to `big_kibana_common_table`
```
indexMappings:
big_kibana_common_table:
sourceIndexes: ["kibana_sample_data_flights"]
```
=> Index <-> tables mappings : fixing field caps and search index resolving

quesma/util/utils.go
Before this change, `MergeMaps` would panic while loading one of the panels in the "Ecommerce" dashboard, because of being unable to compare `[]string` values:
```
panic: runtime error: comparing uncomparable type []string
goroutine 2867 [running]:
quesma/util.MergeMaps.func1({0x103405b60, 0x140069bc0d8}, {0x103405b60, 0x140069bc4e0})
/Users/piotrgrabowski/quesma1/quesma/quesma/util/utils.go:348 +0x5a4
quesma/util.MergeMaps.func2(0x14004cc0cf0, 0x14004cc15c0)
/Users/piotrgrabowski/quesma1/quesma/quesma/util/utils.go:361 +0x134
quesma/util.MergeMaps.func1({0x103406da0, 0x140069bda28}, {0x103406da0, 0x140069bdb48})
/Users/piotrgrabowski/quesma1/quesma/quesma/util/utils.go:286 +0x1598
quesma/util.MergeMaps.func2(0x14004cc0f90, 0x14004cc1020) …
```
=> Fix panic in MergeMaps

quesma/eql/query_translator.go, quesma/model/query.go, quesma/queryparser/aggregation_parser_test.go, quesma/queryparser/query_parser.go, quesma/queryparser/query_parser_test.go, quesma/queryparser/query_translator.go, quesma/quesma/query_translator.go, quesma/quesma/search.go, quesma/quesma/search_opensearch_test.go
We are introducing `ExecutionPlan`. The idea is to keep everything related to processing a single elastic query in a single place. 
We currently keep only a list of queries to execute. 
There is a `QueryResultAdapter` added also. It will be used to implement an alternative way of processing some aggregations. That adapter will adapt alternative results set to the canonical one.
=> Execution plan

quesma/quesma/matchers.go
Before this change trying to access Kibana Fleet subpage in Kibana UI or trying to add a new integration would result in obscure Kibana errors. This was due to a fact that internal Kibana Fleet queries were handled by Quesma, instead of being routed to ElasticSearch.
Fix the problem by extending `matchAgainstKibanaInternal` function to be able to detect Kibana Fleet internal queries. After the fix you can now correctly access those previously failing Kibana Fleet subpages.
=> Detect Kibana Fleet queries in `matchAgainstKibanaInternal`

quesma/quesma/search.go
`removeNotExistingTables` is used in searches with wildcard index patterns to remove indexes which were enabled in a config but without a corresponding table in ClickHouse. However, the logic did not take into account the overrides. For example if index `A` was overridden to `B`, removeNotExistingTables would still search for ClickHouse table `A`, not `B` and wildcard search would return incomplete results.
A disadvantage of this solution is that we are doing Override resolution in yet another place, however I couldn't find a way to do that resolution earlier since later code still needs the original (pre-override) name.
=> Resolve override in `removeNotExistingTables`

quesma/clickhouse/quesma_communicator.go, quesma/quesma/search.go, quesma/quesma/types/translated_sql.go, quesma/quesma/ui/live_tail.go, quesma/quesma/ui/live_tail_drilldown.go
This PR adds the number of returned rows for each query.  You'll be redirected to the Clickhouse console to inspect that query if you click that line.
It contains minor fixes:
- proper context propagation 
- fixed performance results binding
- some code clean
=> Show the number of returned rows

quesma/clickhouse/clickhouse.go, quesma/clickhouse/clickhouse_test.go, quesma/clickhouse/dots.go, quesma/clickhouse/dots_test.go, quesma/clickhouse/insert_test.go, quesma/clickhouse/parser.go
This is quick fix, currently we double create columns:
This removes original `host.name`.
I suggest next week we talk about properly addressing it.
=> Fix handling of field names with `.` from incoming JSONs

quesma/clickhouse/clickhouse.go, quesma/clickhouse/clickhouse_test.go, quesma/clickhouse/insert_test.go
By adding receiver to `buildCreateTableQueryNoOurFields` we can remove `schemaRegistry` passed as arg + unused `config`
=> Removing unused params

examples/kibana-sample-data/quesma/config/local-dev.yaml
The official example doesn't showcase `kibana_sample_data_logs` so there's no need to clutter the configuration file with redundant entries
=> Remove kibana_sample_data_logs from the official example configuration

quesma/proxy/l4_proxy.go, quesma/quesma/functionality/bulk/bulk.go, quesma/quesma/functionality/bulk/bulk_test.go, quesma/quesma/matchers.go, quesma/quesma/router.go, quesma/quesma/router_test.go, quesma/quesma/types/ndjson.go
_bulk requests can write data to many indexes. In particular, a bulk request could contain writes to both enabled and disabled indexes, so some parts of it should be sent to Elastic and some parts to ClickHouse.
Previously the code supported only either sending the entire request to Elastic or sending the inserts to ClickHouse. After this change, the code splits the bulk request into a Elastic and ClickHouse portions and can send it to both endpoints.
The response from Elastic is parsed and "multiplexed" into the final Quesma response (alongside results from ClickHouse). This required some code refactoring and now the code has a proper support for setting response codes/status per each inserted entry.
=> Support sending bulk entries to both Elastic and ClickHouse

.github/workflows/e2e-tests.yml, .github/workflows/pipeline.yml
IT looks all jobs failing, as we use `docker-compose`, but some comments suggest we should use `docker compose`. My attempt to fix it.
=> Fix docker compose in GitHub actions

quesma/queryparser/pancake_model.go, quesma/queryparser/pancake_query_generation.go, quesma/queryparser/pancake_query_generation_test.go, quesma/testdata/aggregation_requests.go
We want all the buckets in `(date) histogram`, so there should be no limit
=> Pancake - quickfix `(date) histogram`

quesma/clickhouse/type_adapter.go, quesma/quesma/functionality/field_capabilities/field_caps.go, quesma/schema/types.go
There's been a bug in case sensitivity - `UInt8` from ClickHouse has defaulted to `text` field in our case.
I'm letting unsigned integers being just integers in ES response for now. We could also make these `unsigned_long`s...
The inconsistency here is that we currently translate integers from CH to longs in ES.
**So perhaps we should translate unsigned integers from CH to unsigned longs in ES (and completely ditch the `integer` type)?** I'm open to your suggestions here.
=> Fix `UInt*` inferred type mapping

quesma/feature/not_supported.go, quesma/feature/not_supported_test.go, quesma/quesma/quesma.go
Filter out internal queries made by Kibana APM and Kibana Fleet in `not_supported.go`. Previously the code would go into `checkIfOurIndex`, query the `indexResolver`, which would prevent Quesma from properly idling.
This code takes a new approach - instead of looking at the index name or parts of request, it now looks at `X-Opaque-Id` header and this seems to be a much cleaner, less hacky way to detect those internal Kibana queries.
=> Filter out Kibana APM/Fleet internal queries

quesma/quesma/mux/mux.go, quesma/quesma/router.go, smoke-test/main.go
Disable the `/_search` endpoint (an endpoint searching over`*` - all indices). This endpoint is used predominantly by internal Kibana queries and it's error-prone/time-consuming to detect those internal Kibana queries. Moreover, Quesma currently doesn't support stitching multiple tables, so a query over many indices wouldn't work well either way.
One of the smoke tests was a test of generating a Kibana Report. Unfortunately, Kibana internally generates this report by querying the `/_search` endpoint. Therefore this commit introduces an alternative way of making sure Kibana works correctly - it now uses an internal search endpoint which is used when one uses the Kibana Discover UI (code written based on observing requests it did).
=> Disable `/_search` (search over all indices)

quesma/queryparser/query_parser.go, quesma/quesma/schema_transformer.go, quesma/quesma/schema_transformer_test.go
In most other `parse*` functions in `query_parser.go`, the incoming field names are first resolved with schema - this takes care of changing `.` to `::`. However, `parseTerm` was missing that call to `ResolveField` and just used the field name as-is (with `.`).
This caused the following query to not work properly:
```
GET index/_search
{
"query": {
"term": {
"nested.clientip": "0.0.0.0/0"
}
}
}
```
Upon fixing `parseTerm`, `applyIpTransformations` had to be fixed - now it receives the "internal name" (`::`), not the original name (`.`) and has to resolve the field accordingly. Additionally, fields with `::` have to be quoted - not wrapped in un-quoted `model.LiteralExpr`.
=> Fix parseTerm to resolve field name

quesma/buildinfo/build.go, quesma/go.mod, quesma/go.sum, quesma/main.go, quesma/quesma/ui/dashboard.go
This PR adds simple "check for updates" functionality. 
We take the latest release from GitHub release API and compare it to currently running version. If new version is available, we log a warning and display beautiful yellow banner in the UI:
(keeping my FE skills sharp 💪)
=> Introducing semver + "check for updates"

quesma/quesma/schema_transformer.go, quesma/quesma/schema_transformer_test.go
Before we used to throw errors when there was `NULL` in a column subject to IP transformation:
```
Cannot convert NULL value to non-Nullable type: while executing 'FUNCTION CAST(destination::ip : 0,
```
This PR addresses this issue by injecting a little `COALESCE` into query, so that in case of null value we fall back to sane default and `CAST` does not fail. Final condition looks like this:
```sql
SELECT *
FROM tablename
WHERE isIPAddressInRange(CAST(COALESCE(columnName, '0.0.0.0') AS "String"),'10.10.10.14/24') 
```
End result:
=> Handle Nullable() columns in IP transformation

quesma/logger/logger.go, quesma/quesma/functionality/terms_enum/terms_enum.go, quesma/quesma/processors.go, quesma/quesma/search.go, quesma/quesma/ui/live_tail.go, quesma/quesma/ui/live_tail_drilldown.go, quesma/quesma/ui/management_console.go, quesma/tracing/context.go
This PR adds the value of the `x-opaque-id` header to the context. `OpaqueId` is shown in the log files and live tab.
I'm not sure if the `OpaqueId` is a good name. Suggestions welcomed.
=> Display `OpaqueId` in the UI

quesma/quesma/functionality/bulk/bulk.go, quesma/quesma/router.go
ElasticSearch Kafka Sink Connector uses the ElasticSearch Java Client v7.17.23 and it failed to deserialize some of the responses from our endpoints.
Firstly, a `_type` field has to be present in the `_bulk` response: https://github.com/elastic/elasticsearch/blob/61d76462eecaf09ada684d1b5d319b5ff6865a83/server/src/main/java/org/elasticsearch/action/DocWriteResponse.java#L116
Secondly, we were missing a response body for `PUT /:index` requests.
=> Fix responses of `_bulk` and `PUT /:index` (for Kafka Sink Connector)

quesma/clickhouse/connection.go, quesma/quesma/config/url.go
For now it's a very blunt and verbose function called only when DB conn pool creation failed completely. 
We might revisit the whole logic in the future, but for now these few simple log lines should make troubleshooting easier.
=> Simple ClickHouse connection doctor impl

quesma/clickhouse/clickhouse.go, quesma/clickhouse/clickhouse_test.go, quesma/clickhouse/insert_test.go, quesma/clickhouse/parser.go, quesma/clickhouse/schema.go
This PR adds functionality of creating new columns instead of putting them into attributes in the case when they will arrive after first insert. It is hidden under feature flag, which is just const for now.
Still, few things ahead:
- new columns addition heuristic
- some config?
- removing `others`
- `BuildInsertJson` cleanup
- more tests
=> Ingest alter table with new columns

quesma/clickhouse/ingest_validator.go, quesma/clickhouse/ingest_validator_test.go
Before this change, if a user manually created a ClickHouse table with a `Int32` column, the validation would reject inserts to that column as it checked that `Int32` column != `Int64` value. Therefore the logic is now extended to support all numeric types (larger/smaller/ floating-point/unsigned). 
Additionally I added range checks that the inserted value actually fits in the column (for example 1000 does not fit in UInt8 column).
=> Fix validation of other numeric types

quesma/queryparser/aggregation_parser.go, quesma/queryparser/pancake_aggregation_parser_metrics.go, quesma/queryparser/pancake_sql_query_generation_test.go, quesma/testdata/aggregation_requests.go
Basically, like in the example test, we had:
```
SELECT count() AS "metric__sample__sample_count_col_0"
```
But should have:
```
SELECT count("host.name") AS "metric__sample__sample_count_col_0"
```
and that's it. 99% sure it's fine now.
=> Pancake - quickfix `value_count` metric aggr

quesma/model/bucket_aggregations/date_histogram.go, quesma/model/bucket_aggregations/histogram.go, quesma/queryparser/pancake_json_rendering.go, quesma/queryparser/pancake_sql_query_generation_test.go, quesma/testdata/aggregation_requests.go, quesma/testdata/aggregation_requests_2.go
Restores logic from old aggregation handling, so we add empty buckets in between if `min_doc_count == 0` in `(date_)histogram`
=> Pancake `date histogram` 2

quesma/ab_testing/collector/collector.go, quesma/ab_testing/collector/diff.go, quesma/ab_testing/collector/fanout.go, quesma/ab_testing/collector/filters.go, quesma/ab_testing/collector/processors.go, quesma/ab_testing/model.go, quesma/ab_testing/sender/sender.go, quesma/jsondiff/elastic_response_diff.go, quesma/optimize/pipeline.go, quesma/quesma/quesma.go, quesma/quesma/search.go, quesma/quesma/search_alternative.go, quesma/quesma/ui/management_console.go
This PR add:
- add support for comparison of  Elastic  vs Quesma responses
- add minor improvements related to storing the results 
- move alternative plan handling to a separate file 
Comparison with an Elastic or other external Quesma can be enabled by:
```
some-index:
enabled: true
optimizers:
elastic_ab_testing:
enabled: true
properties:
mode: "alternative" 
```
Configuration will change in the future.
=> A/B Testing - elastic 

quesma/elasticsearch/mappings.go, quesma/quesma/router.go, quesma/quesma/routes/paths.go
Add a new `PUT /:index/_mapping` endpoint for static mappings. The implementation is similar to the existing `PUT /:index` endpoint, which can also contain a (static) mapping.
Additionally add a previously missing 'double' case to parseElasticType and add a warning message if the parsing failed.
=> Add "PUT /:index/_mapping" endpoint

quesma/queryparser/pancake_sql_query_generation_test.go, quesma/util/sql_pretty_fmt.go, quesma/util/sql_pretty_fmt_test.go
The pretty SQL printer needs to be upgraded to pancake era:
- `ORDER BY` should not cause new line break in window functions
- `SELECT` stmts should break proactive on `,` if next one would not fit in same line
More complex logic, but way nicer, also in live tail.
=> Better sql pretty printer

quesma/model/expr_string_renderer.go, quesma/queryparser/pancake_sql_query_generation.go, quesma/queryparser/pancake_sql_query_generation_test.go, quesma/testdata/aggregation_requests.go, quesma/testdata/aggregation_requests_2.go, quesma/testdata/clients/ophelia.go, quesma/testdata/kibana-visualize/aggregation_requests.go, quesma/testdata/opensearch-visualize/aggregation_requests.go
It turns out that we can generate simpler SQLS:
`sum(aggr_1_part) OVER (PARTITION BY 1)`
`count(*) AS aggr_1_part`
Can be just `sum(count(*)) OVER ()`.
=> Refactor sqls

quesma/model/base_visitor.go, quesma/model/expr.go, quesma/model/expr_string_renderer.go, quesma/model/query.go, quesma/queryparser/aggregation_parser.go, quesma/queryparser/pancake_aggregation_parser_buckets.go, quesma/queryparser/pancake_sql_query_generation.go, quesma/queryparser/query_translator.go, quesma/testdata/aggregation_requests.go, quesma/testdata/aggregation_requests_2.go, quesma/testdata/clients/ophelia.go, quesma/testdata/kibana-visualize/aggregation_requests.go, quesma/testdata/opensearch-visualize/aggregation_requests.go
I simplified the order by implementing it in the first revision of the pancakes. It ignored all but the first order and added its own for dense_rank.
Now:
- We generate all order by's. We need that for correctness.
- We no longer generate order columns if they were part of the key (e.g. `date_histogram`).
- We deduplicate sort.
- We also replaced `Exprs []model.Expr` with `Expr model.Expr` previously we never used it and this was a trap.
This make SQL shorter and more performant. It turn out I had to implement that optimization to make queries correct.
=> Fix pancake order by

quesma/elasticsearch/mappings.go, quesma/quesma/mappings_test.go, quesma/quesma/router.go, quesma/schema/hierarchical_schema.go, quesma/schema/hierarchical_schema_test.go, quesma/schema/schema.go
This commit adds support for `GET /:index` and `GET /:index/_mapping` endpoints. The primary use of those endpoints is to get the (static) mapping of an index. Those endpoints are actively used by some Elastic clients, such as ElasticSearch Kafka Sink Connector.
The implementation generates the mapping based on the schema found in the schema registry.
`hierarchical_schema.go` was introduced since the schema registry stores the schema in a "flat" format (e.g. `products.product_id`, `products.base_price`), but the mapping we need to return should be nested. `SchemaToHierarchicalSchema` in that file transforms the flat schema into a tree (for example `products` is a node with `product_id`, `base_price` children), which is more convenient to use.
The added tests in `mappings_test.go` show …
=> Add "get mapping" endpoints (GET /:index, /:index/_mapping)

quesma/queryparser/pancake_aggregation_parser.go, quesma/queryparser/pancake_sql_query_generation_test.go, quesma/queryparser/pancake_transformer.go, quesma/queryparser/pancake_transformer_test.go, quesma/testdata/aggregation_requests_2.go, quesma/testdata/model.go
Pancakes have quite a few limitations, and only one pancake can be created.
This allows more pancakes to be created per aggregation which brings it closer to feature completion.
=> Many pancakes out of one query

quesma/model/bucket_aggregations/filter.go, quesma/model/bucket_aggregations/no_group_by_interface.go, quesma/model/bucket_aggregations/random_sampler.go, quesma/model/bucket_aggregations/sampler.go, quesma/queryparser/pancake_aggregation_parser.go, quesma/queryparser/pancake_json_rendering.go, quesma/queryparser/pancake_model.go, quesma/queryparser/pancake_sql_query_generation.go, quesma/queryparser/pancake_sql_query_generation_test.go, quesma/queryparser/pancake_transformer.go, quesma/testdata/aggregation_requests.go, quesma/testdata/clients/kunkka.go, quesma/testdata/clients/ophelia.go, quesma/util/sql_pretty_fmt.go, quesma/util/sql_pretty_fmt_test.go
Now, we can use filters in pancakes:
1. It fixes many panels in flight sample dashboards.
2. Feature parity and even exceed original implementation.
While implementing that, I needed to fix some more issues:
- the `doc_count` was ignored in tests, fixed it while also addressing underlying issue
- our query simplification got bugs and fixed that too
The code is a bit more complex, but I prefer smaller ones. After `filters`, `range`, and `dataRange`, I will do the final refactor, though I still need to think through a few cases.
=> Pancake filter implementation

quesma/model/base_visitor.go, quesma/model/bucket_aggregations/dateRange.go, quesma/model/bucket_aggregations/range.go, quesma/model/expr.go, quesma/model/expr_string_renderer.go, quesma/model/noop_visitor.go, quesma/queryparser/aggregation_parser.go, quesma/queryparser/pancake_aggregation_parser_metrics.go, quesma/queryparser/pancake_sql_query_generation.go
Remove two AST types:
- deprecated `StringExpr`
- `MultiFunctionExpr`, it is a weird construct for quantiles, in fact this should be part of a function name. Got discussion with @nablaone
=> Ast cleanup

examples/kibana-sample-data/quesma/config/local-dev.yaml, quesma/clickhouse/parser.go, quesma/clickhouse/table.go, quesma/clickhouse/table_discovery.go, quesma/model/typical_queries/hits.go, quesma/quesma/config/config.go, quesma/quesma/config/index_config.go, quesma/quesma/config/schema_config.go, quesma/quesma/schema_transformer_test.go, quesma/quesma/ui/tables.go, quesma/schema/registry.go, quesma/schema/registry_test.go
Highlights:
* Moving `TypeMappings` and `Aliases` form `IndexConfiguration` to `SchemaConfiguration` (what used to be called `static-schema`, I'm also changing that to `schemaOverrides`
* Cleanup all the deprecated code logic
* There's more to come with the deprecated field changes, so you might see few line commented out here and there as I didn't want this PR to grow too much and conflict with some @nablaone's recent work
**This might look like only configuration syntax change on the surface**, but it actually aims to reduce the usage of configuration and make the code refer to schema instead.
=> Move aliases and types to schema overrides

ci/quesma/config/ci-config.yaml, examples/kibana-sample-data/quesma/config/local-dev.yaml, quesma/clickhouse/table_discovery.go, quesma/config.yaml.template, quesma/feature/not_supported_test.go, quesma/proxy/l4_proxy.go, quesma/queryparser/query_parser_test.go, quesma/quesma/config/config_test.go, quesma/quesma/config/index_config.go, quesma/quesma/config/test_config.yaml, quesma/quesma/config/util.go, quesma/quesma/functionality/bulk/bulk.go, quesma/quesma/functionality/field_capabilities/field_caps.go, quesma/quesma/functionality/field_capabilities/field_caps_test.go, quesma/quesma/matchers.go, quesma/quesma/router.go, quesma/quesma/router_test.go, quesma/quesma/schema_transformer_test.go, quesma/quesma/search_norace_test.go, quesma/quesma/search_opensearch_test.go, quesma/quesma/search_test.go, quesma/quesma/source_resolver.go, quesma/quesma/source_resolver_test.go, quesma/quesma/ui/html_pages_test.go, quesma/quesma/ui/tables.go, quesma/schema/registry_test.go
Removes `enabled: true`, from the index configuration. 
Index being just listed in the configuration by name implies that it is managed by Quesma. 
I'm also adding `disabled: <bool>` option just in case one has WIP configuration yet our logic is completely bypassed.
=> Remove indices `enabled: true` option in favor of explicit disabling

quesma/stats/ingest_statistics.go
Quesma collects statistics for the first `10000` (`STATISTICS_LIMIT`) requests. However the UI incorrectly showed that the stats were collected for more requests than that.
The issue is that `statistics.Requests++` in `Process()` was executed every time, even though `process()` helper stopped looking at those requests. Fix the issue by adding that `STATISTICS_LIMIT` check also to `Process()`.
=> Properly limit count of ingest requests

quesma/model/bucket_aggregations/terms.go, quesma/testdata/aggregation_requests.go, quesma/testdata/aggregation_requests_2.go, quesma/testdata/opensearch-visualize/aggregation_requests.go
`significant_terms` return `doc_count`, not `sum_other_doc_count` like terms.
Fixed here.
=> Return proper response for `significant_terms`, not default from `terms`

quesma/queryparser/query_translator.go, quesma/quesma/functionality/terms_enum/terms_enum.go, quesma/quesma/router.go
Fix for https://github.com/QuesmaOrg/quesma/issues/675
`terms_enum`'s SQL was a) missing `ResolveField` b) didn't fill tablename
Both cases from the issue work now:
I'll add some test.
=> quickfixes to `terms_enum`

ci/quesma/config/ci-config.yaml, quesma/config.yaml.template, quesma/quesma/config/config_v2.go
This PR introduces `pipelines` to the configuration:
```yaml
pipelines:
- name: p-query
frontendConnectors: [ elasticsearch-API-for-kibana ]
processors: [ my-query-processor ]
backendConnectors: [ my-minimal-elasticsearch, my-clickhouse-data-source ]
- name: p-ingest
frontendConnectors: [ elasticsearch-API-for-filebeat ]
processors: [ my-ingest-processor ]
backendConnectors: [ my-minimal-elasticsearch, my-clickhouse-data-source ]
```
This is pretty hairy code, most of it being stubs for future implementation. However, it gets the job done and allows us configuring currently viable deployment scenarios.
=> Pipeline validation

examples/kibana-sample-data/quesma/config/local-dev.yaml
After 5f749e8e5e29c9, `fullTextFields` is now removed and configured by setting a type of field to `text`. Fix the demo config `local-dev.yaml` accordingly.
=> Remove `fullTextFields` from demo config `local-dev.yaml`

quesma/clickhouse/alter_table_test.go, quesma/clickhouse/clickhouse.go
Promotes field to column when it is present more or equal `fieldFrequency` times in last `alwaysAddColumnLimit`
=> Alter column heuristic simplification

quesma/quesma/config/util.go, quesma/quesma/functionality/doc/doc.go, quesma/quesma/router.go
Before this change, the `_doc` endpoint would always report that the insert has succeeded, even if an error occurred and couldn't be handled by Quesma (meaning the insert failed!).
The `RunConfigured` function previously knew about the error, logged it, but did not pass it up to the caller.  Change that and return a properly formatted error response in `doc.go` (`bulk.go` already handled it correctly).
=> Send proper error response in `/_doc` endpoint

quesma/clickhouse/clickhouse.go, quesma/clickhouse/schema.go, quesma/clickhouse/table_discovery.go
The first commit fixes `containsAttributes` method - this method checks if the discovered table has the correct attributes columns. If none are detected, attributes are not updated at all. The method was not updated after 2ea8e07, which changed how the attributes were stored. Fix the problem by referencing correct constants.
The second commit renames a bunch of `Attributes*` constants. After 2ea8e07 attributes are stored in a new way, but constants related to old column names are still there (used internally). This would cause confusion, since the names are very similar. Renaming them to `Deprecated*` makes it more clear (and easier to fix in future PRs).
=> Quick fix containsAttributes and rename Attributes* constants

quesma/clickhouse/clickhouse.go, quesma/clickhouse/parser.go, quesma/clickhouse/table_discovery.go, quesma/jsonprocessor/ingest.go, quesma/jsonprocessor/json_processor.go, quesma/quesma/config/config.go, quesma/quesma/config/index_config.go, quesma/quesma/config/schema_config.go, quesma/schema/registry.go
This is a part of our recent effort of finalizing a new stable configuration. Previously `IgnoredFields` was a part of `IndexConfiguration`, looking like this:
```yaml
test_index:
ignoredFields:
myField: true
anotherField: true
```
However, with the recent improvements to `SchemaConfiguration`, now it makes more sense to configure it under `schemaOverrides`, like this:
```yaml
test_index:
schemaOverrides:
fields:
myField:
ignored: true
anotherField:
ignored: true
```
This PR moves this configuration from `ignoredFields` (`IndexConfiguration`) to `schemaOverrides` (`SchemaConfiguration`).
Moreover, `ignoredFields` did not work correctly with Quesma's ingest, as ignored fields were only ignored in the query path. This PR adds necessary checks also to the ingest path.
Unfortunately, the code …
=> Move IgnoredFields into SchemaOverrides, make it work properly with ingest

quesma/quesma/config/index_config.go, quesma/quesma/config/test_config.yaml, quesma/quesma/schema_transformer_test.go, quesma/quesma/ui/tables.go
After 5f749e8e5e29c9, `fullTextFields` configuration option is now removed, but we forgot to delete it from `IndexConfiguration`, which made it a bit confusing. This commit deletes it fully.
=> Remove last remnants of fullTextFields config

quesma/clickhouse/clickhouse.go, quesma/clickhouse/parser.go
The purpose of this PRs is to unify nested field encoding process, by doing this exactly in one place.
For this reason we have to move generation of `Create Table` string and `insert into` into one function.
=> Nested field encoding, moving encoding into one clearly defined place #1

quesma/optimize/materialized_view_replace.go, quesma/optimize/pipeline.go, quesma/optimize/pipeline_test.go, quesma/queryparser/query_parser.go, quesma/quesma/config/config.go, quesma/quesma/config/index_config.go, quesma/quesma/search_alternative.go
Similarly to indices (ref: https://github.com/QuesmaOrg/quesma/pull/682), optimizers are implicitly enabled when their configuration is in place. There's an option to leave config and make them have no effect by using `disabled` boolean flag.
Old reality:
```
optimizers:
pancake:
Enabled: true
properties:
mode: "apply"
```
Becomes:
```
optimizers:
pancake:
properties:
mode: "apply"
```
or optionally:
```
optimizers:
pancake:
disabled: false
properties:
mode: "apply"
```
FYSA @nablaone.
=> Implicitly enable optimizers when config is there

quesma/queryparser/aggregation_parser_test.go, quesma/queryparser/pancake_sql_query_generation_test.go, quesma/testdata/clients/ophelia.go
Just 2 tests, wanted to get rid of
```
if test.ExpectedPancakeSQL == "" || test.ExpectedPancakeResults == nil { // TODO remove this
t.Skip("Not updated answers for pancake.")
}
```
before going pancake-only.
(those 2 tests were totally unusable before, incorrect results copypasted from some other easier tests, etc., now they actually test something)
=> Update 2 last tests to pancake

quesma/quesma/search.go, quesma/quesma/search_alternative.go, quesma/quesma/ui/live_tail.go
In the Quesma Managment Console we have "Elastic response" panel in the "Live tail" page and similar on the drilldown page. Those panels were filled in by the "EnableElasticsearchIngest: true" mode, which resends all requests to Elastic (even non-ingest!).
However in the upcoming PRs we will effectively remove "EnableElasticsearchIngest" mode. For the query path, it's now obsoleted by A/B testing with Elastic (see #631). But A/B testing with Elastic did not fill in the Quesma Management Console with responses from Elastic.
This PR improves A/B testing with Elastic to also send Elastic's response to the Quesma Management Console.
This is how the relevant panels look like now (previously they were empty):
=> Push Elastic's response from A/B testing to management console

quesma/clickhouse/clickhouse.go, quesma/clickhouse/clickhouse_test.go, quesma/clickhouse/insert_test.go
Propagating the return of type-safe columns as []CreateTableEntry and map[schema.FieldName]CreateTableEntry instead of strings.
=> nested fields encoding, refactoring ddl creation #2

quesma/clickhouse/alter_table_test.go, quesma/clickhouse/clickhouse.go, quesma/clickhouse/clickhouse_test.go, quesma/clickhouse/insert_test.go
This PR:
- changes signature of `BuildIngestSQLStatements` to pass `*table` consequently
- moves body of `GenerateSqlStatements` to `processInsertQuery` to assemble whole workflow in one place and open a way for new arrangement.
=> nested fields encoding #4

quesma/clickhouse/clickhouse.go, quesma/clickhouse/parser.go
This PR implements a major step moving one of nested field encoding functionality to common `processInsertQuery`.
Next,`BuildIngestSQLStatements` will be refactored to extract the same functionality and move it to `processInsertQuery` as well
=> Moving field encoding from JsonToColumns to processInsertQuery

quesma/clickhouse/alter_table_test.go, quesma/clickhouse/clickhouse.go, quesma/clickhouse/clickhouse_test.go, quesma/clickhouse/dots.go, quesma/clickhouse/dots_test.go, quesma/clickhouse/insert_test.go
This PR refactor ingest workflow and unifies ingest field encoding inside `processInsertQuery` function.
That's not finish, it's just a step forward
=> Refactoring - moving ingest field name encoding into one function

quesma/model/bucket_aggregations/date_histogram.go, quesma/testdata/aggregation_requests_2.go
https://github.com/QuesmaOrg/quesma/issues/307
There's still one issue:
Table: (`@timestamp` is in `Asia/Tokyo` zone in Clickhouse)
Query:
It should be `2023-12-01`, as in UTC the year is `2023`
Now it's fine:
=> `date_histogram` timezones last

quesma/model/bucket_aggregations/combinator_aggregation_interface.go, quesma/model/bucket_aggregations/dateRange.go, quesma/model/bucket_aggregations/filter.go, quesma/model/bucket_aggregations/filters.go, quesma/model/bucket_aggregations/range.go, quesma/model/metrics_aggregations/top_metrics.go, quesma/queryparser/aggregation_parser.go, quesma/queryparser/pancake_aggregation_parser_metrics.go, quesma/queryparser/pancake_json_rendering.go, quesma/queryparser/pancake_model.go, quesma/queryparser/pancake_sql_query_generation.go, quesma/queryparser/pancake_sql_query_generation_test.go, quesma/queryparser/pancake_top_hits.go, quesma/queryparser/pancake_transformer.go, quesma/testdata/aggregation_requests.go
Implements `top_metrics`, which brings pancake to parity with previous processing and in some cases exceeding.
This also implements filters/range/dataRange for `top_hits`.
=> Top metrics

quesma/queryparser/pancake_model.go, quesma/queryparser/pancake_transformer.go, quesma/queryparser/pancake_transformer_test.go
Better not to leave pipeline arrays uninitialized as `nil`, I'm 95% sure having both top_hits and pipeline aggregations in 1 request would cause panics because of that. Had that multiple times before.
=> Quickfix: don't leave arrays uninitialized in constructor

quesma/util/utils.go, quesma/util/utils_test.go
Field encoding logic is common and will be used both by ingest and query, so for now I decided to add this logic to `util` package
=> Adding Field encoding logic

quesma/model/bucket_aggregations/date_histogram.go, quesma/quesma/schema_transformer.go
Fix the last flight panel previously we had fair chance of showing error there:
Two fixes:
- if you do * query, even if there is no full-text field, we should default to true
- Implement `min_doc_count` for values different than zero, we also need to change default to `-1`
=> Fix last flight panel

.github/workflows/e2e-tests.yml
Currently we don't run E2E tests on PRs or in merge queue, just on the main branch. That means that someone could merge a PR that ultimately fails on the main branch. Fix that by running E2E tests in the merge queue to catch the issue earlier.
=> Run E2E tests as a required check in merge queue

quesma/model/bucket_aggregations/dateRange.go, quesma/model/bucket_aggregations/range.go, quesma/model/expr.go, quesma/optimize/pipeline_test.go, quesma/queryparser/pancake_aggregation_parser.go, quesma/queryparser/pancake_aggregation_parser_metrics.go, quesma/queryparser/pancake_sql_query_generation.go, quesma/queryparser/pancake_sql_query_generation_test.go, quesma/quesma/schema_transformer_test.go, quesma/quesma/search_test.go, quesma/testdata/aggregation_requests.go, quesma/testdata/aggregation_requests_2.go, quesma/testdata/clients/ophelia.go, quesma/testdata/full_search_requests.go, quesma/testdata/kibana-visualize/aggregation_requests.go, quesma/testdata/opensearch-visualize/aggregation_requests.go, quesma/testdata/opensearch-visualize/pipeline_aggregation_requests.go, quesma/testdata/requests.go, quesma/util/sql_pretty_fmt_test.go, quesma/util/utils_test.go
Two simple changes:
- Unify `count()` to `count(*)`
- Don't generate order count, reuse count column
This optimizes and simplifies queries. Need it, so I can migrate facets to pancakes.
The change is mostly mundane updates of tests.
=> Unify counts

quesma/clickhouse/table_discovery.go
In `config_v2` we initialize the `cfg` with `conf.IndexConfig = make(map[string]IndexConfiguration)` - therefore `nil` check is no longer relevant
=> Tiny fix for table autodiscovery

quesma/clickhouse/table_discovery.go, quesma/quesma/config/config.go, quesma/quesma/matchers.go, quesma/quesma/router.go, quesma/quesma/router_test.go, quesma/quesma/schema_transformer_test.go, quesma/quesma/search.go, quesma/quesma/source_resolver.go, quesma/quesma/source_resolver_test.go, quesma/schema/registry.go, quesma/schema/registry_test.go
Users who haven't specified any table configurations aren't able to create data views today.
1. Because `_resolve` endpoint relies on schema registry, which - as turned out - has never been populated when the index configuration has been missing. 
2. Because `_field_caps` were **not** routed properly.
`matchedAgainstPattern` did rely only on config, not on schema registry, so it couldn't route queries to auto discovered tables. Therefore, timestamp field list has not been expanding and data view could not have been created.
This PR addresses both issues.
**How it works now:**
=> Fix resolving indices when tables are auto-discovered

ci/quesma/config/ci-config.yaml, examples/kibana-sample-data/quesma/config/local-dev.yaml, quesma/quesma/config/config_v2.go, quesma/quesma/config/index_config.go, quesma/quesma/config/test_config_v2.yaml
When configuring indexes, users have a variety of use-cases, such as:
- querying from Elastic, but ingesting into ClickHouse
- querying from ClickHouse and ingesting into ClickHouse
- querying from Elastic, but ingesting into both Elastic and ClickHouse
The existing configuration was not flexible enough to encode those scenarios. This commit adds an additional required config option `target` that specifies the desired source/destination backend connector per each index. Since query and ingest processors are separate, this will allow in the future to have different preferences for query and ingest (not yet in this commit).
This added support in this commit is a bare-minimum support of the `target` config option. For example, it doesn't yet permit dual writes (specifying two targets) or …
=> Add "target" field to index configuration (part 1, bare minimum)

quesma/schema/registry.go, quesma/schema/registry_test.go
Previously `InternalPropertyType` field was only filled-in in only one code path in `populateSchemaFromTableDefinition`. However, it should be filled-in in all cases - table definition is the only source of this information and `populateSchemaFromTableDefinition` is the only place it's filled-in - if it's not correctly set there, it will stay empty forever.
This fixes a problem where "PUT mapping" first filled out the schema registry and `populateSchemaFromTableDefinition` did not update `InternalPropertyType`, leaving it empty, which caused failures on several eCommerce panels (`schema_array_transformer.go` did not get correct `InternalPropertyType`, so it did not perform any required transformation).
=> Always fill-in InternalPropertyType in populateSchemaFromTableDefinition

quesma/clickhouse/table_discovery.go, quesma/proxy/l4_proxy.go, quesma/quesma/config/config_v2.go, quesma/quesma/config/config_v2_test.go, quesma/quesma/config/index_config.go, quesma/quesma/config/test_config_v2.yaml, quesma/quesma/config/util.go, quesma/quesma/functionality/bulk/bulk.go, quesma/quesma/functionality/doc/doc.go, quesma/quesma/functionality/field_capabilities/field_caps.go, quesma/quesma/functionality/field_capabilities/field_caps_test.go, quesma/quesma/matchers.go, quesma/quesma/router.go, quesma/quesma/router_test.go, quesma/quesma/search_test.go, quesma/quesma/source_resolver.go, quesma/quesma/source_resolver_test.go, quesma/quesma/ui/tables.go, quesma/schema/registry_test.go
This commit removes the `disabled` option from index configuration, as it's now possible to reflect it via target configuration:
Previously:
```yaml
my_index:
disabled: true
```
Now:
```yaml
my_index:
target: [ "my-elastic-connector" ]
```
This highlights a problem with `disabled` - it meant that the index should be read/written from Elastic, but a user might have incorrectly thought that `disabled` means that all queries to the index will get rejected.
Upon removing `disabled`, all internal Quesma code is now modified to use the `QueryTarget` and `IngestTarget` arrays directly, paving the way for more flexible target configuration in the future (next PRs).
=> Remove "Disabled" from index conf, switch code to use QueryTarget, IngestTarget

quesma/clickhouse/parserCreateTable.go, quesma/clickhouse/table_discovery.go, quesma/clickhouse/util.go, quesma/ingest/insert_test.go, quesma/ingest/parser.go, quesma/ingest/processor.go, quesma/ingest/processor_test.go, quesma/jsonprocessor/ingest.go, quesma/model/typical_queries/hits.go, quesma/queryparser/pancake_aggregation_parser_metrics.go, quesma/quesma/schema_array_transformer.go, quesma/quesma/schema_map_transformation.go, quesma/quesma/schema_transformer.go, quesma/quesma/schema_transformer_test.go, quesma/quesma/search.go, quesma/quesma/search_opensearch_test.go, quesma/quesma/search_test.go, quesma/quesma/transformations.go, quesma/schema/registry.go, quesma/schema/static_registry.go, quesma/schema/types.go, quesma/testdata/opensearch_requests.go, quesma/testdata/requests.go, quesma/testdata/requests_with_special_characters.go, quesma/util/utils.go, smoke-test/main.go
This PR introduces changes for field encodings according to defined criteria by https://github.com/QuesmaOrg/quesma/blob/main/adr/5_nested_fields_representation.md
Fields are encoded during ingest with original name stored as comment
=> Schema field encoding additions

quesma/model/metrics_aggregations/extended_stats.go, quesma/testdata/aggregation_requests.go
Fix for some edge case. `extended_stats` uses 10 Clickhouse functions, even though it seems like all of them return nulls
2 of them can actually return `NaN` (those 2 nulls above are in fact `NaN`) (`varSamp` and `stddevSamp` both divide by `N-1`, when sample N is `1`, we get a `NaN` here)
We need to return `"NaN"` as string for Kibana to digest it, and that's done in this PR.
Before:
After:
=> Quickfix `extended_stats`

quesma/end_user_errors/end_user.go, quesma/eql/query_translator.go, quesma/model/query.go, quesma/model/typical_queries/hits.go, quesma/queryparser/aggregation_parser_new_logic_test.go, quesma/queryparser/aggregation_parser_test.go, quesma/queryparser/aggregation_percentile_parser_test.go, quesma/queryparser/lucene/expression.go, quesma/queryparser/lucene/lucene_parser.go, quesma/queryparser/lucene/lucene_parser_test.go, quesma/queryparser/pancake_aggregation_parser_buckets.go, quesma/queryparser/pancake_sql_query_generation_test.go, quesma/queryparser/query_parser.go, quesma/queryparser/query_parser_async_search_test.go, quesma/queryparser/query_parser_range_test.go, quesma/queryparser/query_parser_test.go, quesma/queryparser/query_translator.go, quesma/queryparser/query_translator_test.go, quesma/quesma/functionality/terms_enum/terms_enum.go, quesma/quesma/functionality/terms_enum/terms_enum_test.go, quesma/quesma/query_translator.go, quesma/quesma/schema_transformer.go, quesma/quesma/schema_transformer_test.go, quesma/quesma/search.go, quesma/quesma/search_alternative.go, quesma/quesma/search_norace_test.go, quesma/quesma/search_opensearch_test.go, quesma/quesma/transformations.go
This PR adds support for querying multiple indexes.  It's limited to indexes stored in `common table`.
There are a few things to do:
- check why some columns are not translated properly (see `handleDottedTColumnNames` transformer)
- `table.Clickhouse` removal from `ClickhouseQueryTranslator`
- testing, more testing
=> Common table - query multiple indexes 

quesma/quesma/schema_transformer.go
Small regression I've found while working on auth. In auto discovery mode, there's no index configuration, so we shall fallback to `false` for `useCommonTable` instead of returning an error
=> Fix `applyPhysicalFromExpression` for auto-discovery

quesma/quesma/config/config_v2.go, quesma/quesma/config/index_config.go, quesma/quesma/functionality/doc/doc.go, quesma/quesma/router.go
This PR makes it possible to configure dual writes by specifying two targets in ingest processor:
```yaml
my_index:
target: [ my-clickhouse-data-source, my-minimal-elasticsearch ]
```
The limitation, that the ingest processor and query processor must have the same configuration, is now lifted (so you can specify reading from Elastic, but ingesting into both ClickHouse and Elastic).
The implementation of `/_doc` endpoint is now simplified to use the existing logic of bulk ingest (which already had a proper support for dual writes).
=> Dual write support in index config

quesma/quesma/config/config_v2.go
This if now doesn't make much sense, won't catch `len == 0` case, and we'll get panic in the next line.
After change it matches the error msg.
=> config: 1-line quickfix

quesma/elasticsearch/client.go, quesma/elasticsearch/client_test.go, quesma/quesma/functionality/bulk/bulk.go
Fixing ingesting to password-protected Elasticsearch cluster.
As a bonus I've cleaned up another accidental usage of `client := http.Client{}` and added some tests.
=> Fixing ingest to authenticated Elasticsearch

quesma/clickhouse/table_discovery.go, quesma/comment_metadata/comment_metadata.go, quesma/comment_metadata/comment_metadata_test.go, quesma/common_table/const.go, quesma/ingest/insert_test.go, quesma/ingest/parser.go, quesma/ingest/processor.go, quesma/schema/registry.go
This PR changes the way we store metadata in column comments. Now we store it as a structure.
=> Database Column Comments as Metadata Storage – Part 2

quesma/quesma/schema_transformer.go
So because Hydrolix is case-sensitive, our encoding algorithm has produced an incorrect query - Quesma ended up throwing `Field not found in the database` error.
=> Fix field encoding for Hydrolix

quesma/quesma/quesma.go
Quesma is noisy if we have no auth header.
=> Suppress warning - no auth setup

ci/quesma/config/ci-config.yaml
Add missing `*` configuration in `ci-config.yaml`. This caused E2E tests to fail.
=> Missing `*` in ci-config.yaml

quesma/queryparser/query_translator.go
I'll add tests in a next PR https://github.com/QuesmaOrg/quesma/pull/793 For now, need a quick fix merged ASAP.
Before:
After:
=> Fix count (quick)

quesma/clickhouse/clickhouse.go, quesma/clickhouse/connection.go, quesma/connectors/connector.go, quesma/quesma/config/config_v2.go, quesma/quesma/config/test_configs/quesma_as_transparent_proxy.yml
As in the description. The way I did it is quite ugly (esp. the `(l *LogManager) IsInTransparentProxyMode()`), but for now I think it's a decent compromise.
=> Remove the need for SQL-type backend connector in transparent proxy mode

ci/quesma/config/ci-config.yaml, examples/kibana-sample-data/quesma/config/local-dev.yaml, quesma/quesma/config/config.go, quesma/quesma/config/config_v2.go, quesma/quesma/config/test_configs/quesma_adding_two_hydrolix_tables.yaml, quesma/quesma/config/test_configs/test_config_v2.yaml
Revert the `*` functionality in index configuration. For the time being (for the next release), users of Quesma will have to explicitly mention all enabled indexes and autodiscovery is not supported.
Please note that as of this commit, if some index X is not configured, Quesma will route queries/ingest to index X into ElasticSearch.
=> Revert `*` functionality

quesma/licensing/runner.go, quesma/logger/logger.go, quesma/main.go, quesma/quesma/config/config.go, quesma/quesma/config/config_v2.go
Before this change if the user did not configure the log level in the configuration it would default to `DEBUG` (as this is the first entry in `DebugLevel` enum). Debug log level is very verbose and it's not a great experience for a user (who tried a minimal config).
Therefore set log level to `INFO` if none was provided in the loaded config.
=> Change default log level to `INFO`

ci/quesma/config/ci-config.yaml, examples/kibana-sample-data/quesma/config/local-dev.yaml, quesma/quesma/config/config.go, quesma/quesma/config/config_v2.go, quesma/quesma/config/index_config.go, quesma/quesma/config/schema_config.go, quesma/quesma/config/test_configs/quesma_adding_two_hydrolix_tables.yaml, quesma/quesma/config/test_configs/quesma_hydrolix_tables_query_only.yaml, quesma/quesma/config/test_configs/test_config_v2.yaml
Remove the requirement that the user has to configure some index in both ingest and query processors. After this change, the user can now define an index only in ingest or only in query processor.
Under the hood, the translated V1 index configuration will have an ingest target set to `DefaultIngestTarget` if index is missing from ingest processor configuration or query target set to `DefaultQueryTarget` if index is missing from query processor configuration.
Bring back required `*` configuration. The only supported configuration is `"*": target: [elastic]`. This will make it easier for the users to understand the configuration, instead of relying on some "magic" fallback behavior.
Additionally improve the logging of index configurations (printed at the start of Quesma).
=> Remove requirement of defining indexes in both processors, bring back required `*` configuration

.github/workflows/docker-image-latest.yml, .github/workflows/release.yml, ci/ci.yml, ci/e2e.yml
Changes to how we build/publish Quesma Docker images:
* what used to be `quesma/quesma:latest` now becomes a pointer to **latest released version**
* introducing `quesma/quesma:nightly` image which becomes the most recent (not necessarily released/stable) version, always built and pushed from the `main` branch
* removing image pushes to GCR for  `quesma/quesma:nightly`. Release images will stay, as GCP's products don't support pulling from DockerHub (😢)
=> Introduce `nightly` Docker tag

quesma/elasticsearch/client.go, quesma/elasticsearch/client_test.go
`Request()` and `RequestWithHeaders()` methods of elasticsearch client always "JSON marshalled" the incoming payload (body). However all users of those methods actually already gave a JSON marshalled payload! This caused the request body to be double marshalled, resulting in some strange base64 blob, which broke our double writes (sending bulk to Elastic).
Fix the problem by NOT marshalling in `Request*()` methods. Improve the `client_test.go` to validate that the client did not tamper with the body.
=> Fix double JSON marshalling in elasticsearch client's Request*()

quesma/main.go, quesma/quesma/config/config.go, quesma/quesma/config/config_v2.go, quesma/quesma/config/config_v2_test.go, quesma/quesma/config/test_configs/has_common_table.yaml, quesma/quesma/config/test_configs/invalid_dual_target.yaml
We should create the common table if there is an index using it. In other cases, it emits unnecessary logs. 
It fixes a bug while processing the config.
=> Create common table if needed

quesma/queryparser/query_translator.go, quesma/quesma/search.go
We return `completion_status` HTTP code which causes bug in certain version of Kibana.
=> Fix completion_status bug

quesma/model/bucket_aggregations/histogram.go, quesma/testdata/aggregation_requests_2.go
When `interval` is any other than `1`, we receive a float, so no change needed (as we do `(field / interval) * interval` and it's a float even if `interval` is an integer, like `2` (tested))
When `interval` is `1`, we get any type the field is in DB, as we just do `SELECT field`, so we need to check all int/float types. Added that here.
Before:
After:
=> Fix histogram when `interval==1`

quesma/kibana/intervals.go, quesma/model/bucket_aggregations/date_histogram.go, quesma/queryparser/aggregation_parser_test.go, quesma/testdata/dates.go
Query from the test caused Quesma to crash without any error message, as it'd run of out memory in 0,1s or so. You can see it below:
It was a small bug when adding empty rows. Usually keys in `date_histogram` are `x, x+1, x+2,...`, when we're using `timestamp / duration` as a key, so number of added empty rows was kind of limited. But in `calendar_interval` for big intervals, like 1 week, keys are timestamps in millisecond, so we were adding a new row for each millisecond, exhausting all the memory very quickly.
Fixed here by considering the second option.
=> Fix problems with dates part 1

quesma/queryparser/pancake_sql_query_generation_test.go, quesma/testdata/aggregation_requests.go
No changes in the code, just tests.
Completed 2 tests. Old logic had some problems with them, that is with subaggregations results missing (being empty) for some of the more top-level keys.
Pancakes seem to be handling it correctly, so no changes in the code were needed.
=> Unskip 2 tests

quesma/optimize/pipeline.go, quesma/quesma/search.go
This request caused panic
```
POST /logs*/_search
{
"_source": false,
"fields": [
{
"field": "*",
"include_unmapped": "true"
},
{
"field": "reqTimeSec",
"format": "strict_date_optional_time"
}
],
"highlight": {
"fields": {
"*": {}
},
"fragment_size": 2147483647,
"post_tags": [
"@/kibana-highlighted-field@"
],
"pre_tags": [
"@kibana-highlighted-field@"
]
},
"query": {
"bool": {
"filter": [
{
"range": {
"timestamp": {
"format": "strict_date_optional_time",
"gte": "2024-10-01T11:12:46.174Z",
"lte": "2024-10-14T11:27:46.174Z"
}
}
}
],
"must": [],
"must_not": [],
"should": []
}
},
"runtime_mappings": {},
"script_fields": {},
"size": 0,
"sort": [
{
"timestamp": {
"format": "strict_date_optional_time",
"order": "desc",
"unmapped_type": "boolean"
}
},
{
"_doc": {
"order": "desc",
"unmapped_type": …
```
=> Quickfix panic at Hdx

quesma/model/bucket_aggregations/date_histogram.go, quesma/model/bucket_aggregations/date_histogram_test.go, quesma/model/pipeline_aggregations/average_bucket.go, quesma/model/pipeline_aggregations/common.go, quesma/model/pipeline_aggregations/cumulative_sum.go, quesma/model/pipeline_aggregations/derivative.go, quesma/model/pipeline_aggregations/max_bucket.go, quesma/model/pipeline_aggregations/min_bucket.go, quesma/model/pipeline_aggregations/pipeline_aggregation.go, quesma/model/pipeline_aggregations/serial_diff.go, quesma/model/pipeline_aggregations/sum_bucket.go, quesma/model/pipeline_query_type.go, quesma/queryparser/pancake_sql_query_generation_test.go, quesma/queryparser/pancake_transformer.go, quesma/testdata/opensearch-visualize/pipeline_aggregation_requests.go
Unskips one test.
We had a problem when generating results for pipeline aggregations, because if bucket's key was a date, pipeline aggregation only had what it received from DB (usually some random int, result of `date_field.ToUnixTimestamp() / interval_duration`, let's call it `X` (`originalKey` in the new code)), and had no idea how to transform it into a valid date in response.
I fixed that by connecting pipeline aggregation to its parent bucket aggregation, so now pipeline aggregation knows that its parent is a date_histogram, and if it is, it asks it to transform `X -> proper date`
=> Fix dates in pipeline aggregations

quesma/model/simple_query.go, quesma/queryparser/query_parser.go, quesma/queryparser/query_translator_test.go
This `Fieldname` thankfully isn't used anywhere anymore.
Can close https://github.com/QuesmaOrg/quesma/issues/10 afterwards.
=> Remove relic code

quesma/model/bucket_aggregations/range.go, quesma/model/metrics_aggregations/top_hits.go, quesma/queryparser/aggregation_parser.go, quesma/queryparser/pancake_json_rendering.go, quesma/queryparser/pancake_sql_query_generation.go, quesma/queryparser/pancake_sql_query_generation_test.go, quesma/testdata/opensearch-visualize/aggregation_requests.go
* Fixes some small problem with not having count in `top_hits` pancake. We can't get it (at least easily) in our logic, as you can't do `SELECT field, count()`. But it doesn't seem to be a problem, it's of course present in some other pancake and it's only taken from there => seems working fine.
* Add some better support for what fields we want to return in `top_hits`. Before it had to be an array `params[_source][includes]`, now it can also. be a string `params[_source]`. It's not 100% support for this `_source` field, but a bit better.
=> small improvement `top_hits`

quesma/quesma/matchers.go, quesma/quesma/router_test.go
Over the course of development of Quesma, `matchedAgainstPattern` has increased in complexity. This commit rewrites and simplifies the implementation and adds a couple new test cases.
=> Rewrite, simplify `matchedAgainstPattern`

quesma/quesma/quesma.go, quesma/quesma/search.go
Primarily it is to remove one warning when we delete async_queries.
=> Minor HTTP endpoint improvement

.github/workflows/integration-tests.yml, ci/it/testcases/base.go, ci/it/testcases/utils.go
Adding few tweaks so that test **run on CI** (wasn't that straightforward TBH) and are not flaky. 
Overall, those two ITs on GitHub worker have never took more than 3 minutes total, which I think as for IT is pretty decent.
For now, running only `quesma/quesma:latest` docker image upon request. Later we can discuss when/where we want them to be kicked off.
=> Adding GitHub Workflow for integration tests

quesma/quesma/schema_map_transformation.go
This PR removes a workaround, i.e direct call to `util.FeldToColumnEncoder` and use schema to resolve internal name
=> Get rid of FieldToColumnEncoder call

quesma/quesma/config/config_v2.go, quesma/quesma/config/config_v2_test.go, quesma/quesma/config/test_configs/ingest_with_single_connector.yaml, quesma/quesma/config/test_configs/quesma_as_transparent_proxy_without_noop.yml
Previously, the user always had to provide two backend connectors to the query/ingest processor: Elastic connector and SQL-type connector (aka ClickHouse/Hydrolix).
Remove that requirement - now only the Elastic connector is mandatory (for Kibana internal queries) and the user doesn't need to have SQL-type backend connector in the pipeline (in such case they won't be able to use it in `indexes` configuration, thus only targeting queries/ingest to Elastic).
However, this doesn't yet solve the more tricky scenario of completely removing SQL-type backend connector from the entire configuration (it's possible in transparent proxy mode, but not yet in dual pipeline mode). Put another way: ClickHouse/Hydrolix is still required in the `backendConnectors` section (except in no-op transparent …
=> Remove the need for SQL-type backend connector in query/ingest processors and pipelines

examples/kibana-sample-data/quesma/config/local-dev.yaml
These are by default set per [config_v2.go#L99-L100](https://github.com/QuesmaOrg/quesma/blob/main/quesma/quesma/config/config_v2.go#L99-L100) so there's no point in explicitly listing them in the demo conf.
=> Remove `internalTelemetryUrl` and `logging.remoteUrl` from quickstart demo config

.github/workflows/build-quesma-docker-image.yml, .github/workflows/nightly-docker-build-and-push.yml
A hot fix after 0c220f988a947ca63f3ca51c65a4ba05a2162f13. After it was merged, the reusable workflow ("child workflow") doesn't get the secrets (docker credentials) by default, resulting in a job failure.
Fix the issue by specifying the needed secrets for the reusable workflow.
The secrets are not required if `PUSH` doesn't happen and only the `nightly-docker-build-and-push.yml` workflow actually passes those secrets.
=> Get secrets (Docker login credentials) in `build-quesma-docker-image.yml`

quesma/schema/registry.go
The comment in the code pretty much sums it up.
A very nasty bug caused by side-effecting nature of schema/encoding management :)
=> Fix updating encodings based on PUT `*/_mapping`

.github/workflows/build-quesma-docker-image.yml, .github/workflows/integration-tests.yml, ci/it/testcases/utils.go
The `latest` tag of `quesma/quesma` is the latest released stable release of Quesma, while `nightly` is the newest build of Quesma. Integration tests used to run against `quesma/quesma:latest` and not the last `nightly` build of Quesma, which meant that we wouldn't catch some failures before release.
Fix this issue by running the integration tests against `nightly` and always building the newest `quesma/quesma:nightly` in the `integration-test.yml` GitHub workflow.
=> Run integration tests against `nightly` (not `latest`)

quesma/clickhouse/table_discovery.go
After 7611ebac683e5e2fc326ea3afac8f80b3abf37e1, the table resolver always asks table discovery to refresh table information. However, in the transparent proxy case, Quesma doesn't make any connections to ClickHouse, therefore `td.dbConnPool` can be `nil`, resulting in `nil` pointer panic.
Add missing `nil` check, the existing code now can gracefully handle this situation. 
In the future we might improve Quesma's main to not construct `table_discovery` if there is no ClickHouse connector.
=> Fix `nil` pointer panic in `table_discovery.go`

quesma/go.mod, quesma/go.sum, quesma/quesma/config/config_v2.go, quesma/quesma/config/config_v2_test.go, quesma/quesma/config/env2json.go, quesma/quesma/config/env2json_test.go
While creating demo env variable, I noticed it is impossible to pass credentials by variable. Unfortunately, `koan` does not support overriding YAML arrays directly, so I had to add this functionality.
=> Allow env variables

quesma/quesma/schema_array_transformer.go
It fixes this panel: 
```
2024-10-11 16:32:13 Oct 11 14:32:13.599 ERR quesma/quesma/recovery/recovery_strategies.go:32 > Panic recovered: interface conversion: interface {} is model.SelectCommand, not *model.SelectCommand
2024-10-11 16:32:13 goroutine 482 [running]:
2024-10-11 16:32:13 runtime/debug.Stack()
2024-10-11 16:32:13     /usr/local/go/src/runtime/debug/stack.go:26 +0x64
2024-10-11 16:32:13 quesma/quesma/recovery.commonRecovery({0x6857e0, 0x40005f0990}, 0x4000875da8?)
2024-10-11 16:32:13     /quesma/quesma/recovery/recovery_strategies.go:32 +0x154
2024-10-11 16:32:13 quesma/quesma/recovery.LogAndHandlePanic({0x8e22b0, 0x40005f8690}, 0x4000877940)
2024-10-11 16:32:13     /quesma/quesma/recovery/recovery_strategies.go:51 +0x68
2024-10-11 16:32:13 panic({0x6857e0?, 0x40005f0990?}) …
```
=> Fix array transformation panic 

.github/workflows/build-quesma-docker-image.yml, .github/workflows/e2e-tests.yml, .github/workflows/generate-notice.yml, .github/workflows/integration-tests.yml, .github/workflows/pipeline.yml, .github/workflows/release.yml, README.md, ci/e2e-data-generator/go.mod, quesma/go.mod, quesma/optimize/cache_queries.go, quesma/queryparser/pancake_sql_query_generation.go, quesma/queryparser/pancake_transformer.go, quesma/quesma/config/config.go, quesma/quesma/config/config_v2.go, quesma/quesma/functionality/terms_enum/terms_enum.go, smoke-test/go.mod
Move to the latest version. Bunch of small changes, but now it is possible to iterate over custom types:
https://go.dev/blog/range-functions
=> Upgrade go lang

.github/workflows/integration-tests.yml, ci/it/configs/quesma-with-dual-writes-and-common-table.yml.template, ci/it/configs/quesma-with-two-pipelines.yml.template, ci/it/integration_test.go, ci/it/testcases/test_dual_write_and_common_table.go, ci/it/testcases/test_reading_clickhouse_tables.go, ci/it/testcases/test_transparent_proxy.go, ci/it/testcases/test_two_pipelines.go
These should really boost our confidence when making changes, esp. w.r.t routing and configuration (but not only of course 😉) 
Full suite run on GitHub CI lasts <4 minutes. Locally <2 minutes given all the images are available.
=> Adding some integration tests

.github/workflows/integration-tests.yml, ci/it/integration_test.go, ci/it/testcases/base.go, ci/it/testcases/test_dual_write_and_common_table.go, ci/it/testcases/test_reading_clickhouse_tables.go, ci/it/testcases/test_transparent_proxy.go, ci/it/testcases/test_two_pipelines.go, ci/it/testcases/utils.go
Addressing [review feedback](https://github.com/QuesmaOrg/quesma/pull/876#discussion_r1799110940) for which PR has been merged prematurely
=> Add license headers to ITs 

.github/go-licence-detector/overrides.ndjson
`github.com/mrjones/oauth` uses a non-standard-named filename for the `LICENSE.txt` file (`MIT-LICENSE.txt` instead of `LICENSE.txt`). `go-license-detector` cannot handle such a case, as seen here: https://github.com/QuesmaOrg/quesma/actions/runs/11327943230/job/31500069625
The problem was already reported to both the `go-licenses` library (https://github.com/google/go-licenses/issues/142) and the `oauth` library (https://github.com/mrjones/oauth/issues/74), but it's not fixed yet.
Fix the problem by adding an override entry to `overrides.ndjson`.
=> Add license override for oauth library

ci/it/testcases/test_dual_write_and_common_table.go, ci/it/testcases/test_reading_clickhouse_tables.go, ci/it/testcases/test_transparent_proxy.go, ci/it/testcases/test_two_pipelines.go
Using `t.Run(` (see [Go docs](https://pkg.go.dev/testing#T.Run)) to have each function as a separate test.
Looks pretty neat in IDE and will make tracing errors in the future easier 😉
=> Separate test functions into `t.Run()`'s

quesma/quesma/config/config_v2.go, quesma/table_resolver/rules.go
A user in the configuration of a query/ingest processor can define targets:
```yaml
my_index:
target: [ elastic-conn, clickhouse-conn ]
```
We subsequently take those values and populate `QueryTarget` and `IngestTarget` arrays based on it, however the code did not preserve the order of the targets. The order is important for A/B testing case and `rules.go` had to incorrectly allow an unsupported scenario for everything to work correctly.
Fix the issue by preserving the same order in `QueryTarget`, `IngestTarget` as in the original `target` user configuration. `rules.go` workaround can be now removed.
=> Preserve order of targets in QueryTarget, IngestTarget

ci/it/testcases/utils.go
We should fail the test on Quesma's startup failure.
=> IT - Fix error handling

quesma/quesma/ui/console_routes.go
We must provide keys for session storage (gothic and guerillla) to work with SSL.  Both frameworks switch to secure cookies on SSL. 
The solution is to generate keys on on start. This is for now.  This is not a final solution.
=> Make secure cookies working

ci/it/testcases/base.go, ci/it/testcases/test_dual_write_and_common_table.go, ci/it/testcases/test_reading_clickhouse_tables.go, ci/it/testcases/test_transparent_proxy.go, ci/it/testcases/test_two_pipelines.go
Since I'll be adding new integration tests, let's do some cleanup of boilerplate of existing tests to make it nicer to write new tests (avoiding further code duplication/boilerplace).
This PR tackles `RequestToQuesma`: move error handling/reading of body into `RequestToQuesma` function itself - no need to duplicate this logic all over the test code.
=> ITs: RequestToQuesma boilerplate cleanup

quesma/quesma/router.go
Previously it resulted in:
```
curl -XPUT localhost:8080/test2
Q1001: Invalid request body. We're expecting JSON here.
Request ID: 0192b9db-b87f-7553-b7de-8d108e2f326d
```
Now it's still just an internal no-op and positive response to the client
```
curl -XPUT localhost:8080/test2
{"acknowledged":true,"shards_acknowledged":true,"index":"test2"}%
```
**Context:** In Elasticsearch world, just creating index using  `PUT /indexName` request (without mappings or settings) is pretty standard practice, so we should respect that, even though that's a no-op in our realm .
=> Handle empty body `PUT /:index` request

quesma/quesma/config/config.go, quesma/quesma/config/config_v2.go, quesma/table_resolver/rules.go
This PR is about `usingCommonTable` configuration property for `*` wildcard:
```
'*':
```
=> Use common table for '*' wildcard

quesma/quesma/schema_transformer.go, quesma/quesma/schema_transformer_test.go, quesma/quesma/search.go
This is PR to handle queries  where following configuration is used (no explicit index configuration)
```
'*':
```
=> Using `UseCommonTableForWildcard`property for wildcard config

.github/workflows/integration-tests.yml
`set-output` is deprecated (https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) and the job always printed annoying warning because of that. Fix that to use `$GITHUB_OUTPUT` instead.
Additionally, instead of printing just a hash of the commit, print a (clickable) URL to the commit.
=> Fix usage of deprecated `set-output`, give nicer URL to commit

quesma/queryparser/lucene/expression.go, quesma/queryparser/lucene/lucene_parser.go, quesma/queryparser/lucene/lucene_parser_test.go, quesma/queryparser/lucene/token.go
This Lucene parser seemed to work fine for a subset of Lucene. Now I had to extend this subset a bit, and I'm afraid some weird (and usually incorrect) queries might not work 100% correctly, although I'd have to think for a bit for an example.
But all tests + customer's dashboards work fine, so I'd merge it. I have an idea how to support full Lucene, 90% it'd work. I'll try to do it very soon.
I tried 2 other open-source Lucene parsers, and they both fail on ~20-30 / 60 our tests, so if our passes all, it's more fine than not.
=> Lucene enhancements

quesma/quesma/ui/console_routes.go
Our Set-cookie was pretty legit:
```
quesma-session=...blah...; Path=/; Expires=Thu, 28 Nov 2024 20:59:59 GMT; Max-Age=2592000; Secure; SameSite=None
```
yet it was enigmatically rejected by Safari. Took me while but it turns out that for `localhost` Safari does not allow `Secure` cookie 😕 
So now, `Set-Cookie` will be just `quesma-session=...blah...`. I think for this admin interface it's just fine - at least for now, when we don't really allow custom domains, ssl, etc.
=> Fix login to admin console on Safari

quesma/ingest/processor.go
This PR adds a sanity check and fixes crash. I plan to work on root cause of the problem is next PR
```
Oct 30 14:15:34.699 INF quesma/functionality/bulk/bulk.go:339 > Ingesting via _bulk API, batch size=6 documents
Oct 30 14:15:35.882 ERR quesma/recovery/recovery_strategies.go:32 > Panic recovered: runtime error: invalid memory address or nil pointer dereference
goroutine 155 [running]:
runtime/debug.Stack()
/Users/pdelewski/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.2.darwin-arm64/src/runtime/debug/stack.go:26 +0x64
quesma/quesma/recovery.commonRecovery({0x102e930a0, 0x103359030}, 0x1400033a380?)
/Users/pdelewski/Projects/quesma/quesma/quesma/recovery/recovery_strategies.go:32 +0x154
quesma/quesma/recovery.LogPanic()
/Users/pdelewski/Projects/quesma/quesma/quesma/recovery/recovery_str …
```
=> Adding table sanity check

quesma/quesma/config/config_v2.go, quesma/quesma/ui/dashboard.go
Disables latest version checking and log upload when telemetry is disabled. It disables a lot of noisy logs in air-gapped version.
=> Disable telemetry

quesma/clickhouse/table_discovery.go
Following config 
```
'*':
```
lead to wrong decision about using `common table`
=> Discovered table should not be virtual by default

docs/public/docs/limitations.md
After the recent reorganization of documentation this section was lost. Bring it back to `limitations.md` file. Note that this section was originally on the "Getting started" page, but now it's on the "Limitations" page.
=> Bring back "Software and hardware requirements" section

docs/public/docs/limitations.md
Currently Quesma auto-creates tables with `MergeTree` engine. It's automatically converted to `ReplicatedMergeTree` in case of ClickHouse Cloud, but not in case of a local multi-node cluster and the user can't control it.
If the user has a local multi-node cluster, the tables automatically created by Quesma won't be replicated - the only solution is to create them manually with the correct `ReplicatedMergeTree` engine.
Refs #934
=> Add "ClickHouse engine" limitation

quesma/clickhouse/connection.go, quesma/quesma/config/config_v2.go, quesma/quesma/config/url.go
This PR improves the validation of connection URLs in configuration, giving clearer error messages to the user and the expected format of the connection string.
Related to that, RemoteLogDrainUrl and QuesmaInternalTelemetryUrl now can't be provided in the config - they were overwritten by hardcoded constants either way.
Additionally, ClickHouse connection doctor is improved:
- If connection succeeded it suggests making sure that username/password is correct
- It now skips TLS trial connections if the user disabled TLS in the config (and informs of that fact)
- It tries default ports in more cases
This PR is extracted from larger PR #938.
=> Improve connection doctor and validation of connection URLs

quesma/quesma/config/config_v2.go, quesma/quesma/config/config_v2_test.go, quesma/quesma/config/index_config.go, quesma/quesma/config/test_configs/target_new_variant.yaml
This PR implements new variant of `target` configuration where it's a list not an array and can have more attributes (potentially in the future)
Current variant is still supported and is a fallback in the case extended version is missing
Below
```
kibana_sample_data_flights:
target:
- my-clickhouse-data-source:
```
is equivalent of 
```
kibana_sample_data_flights:
target: [my-clickhouse-data-source]
```
PR contains a bit of duplicated code, something that I would prefer fix in next PR.
=> Target config extended configuration

quesma/quesma/config/config_v2.go
Disallow `schemaOverrides` in configuration of `*` index, since that functionality does not work correctly right now. Note that in the future we might lift this restriction (if we fix the implementation).
Documentation of this limitation will be included in #950.
=> Disallow `schemaOverrides` in `*` configuration

quesma/quesma/ui/ab_testing.go
The first column should be "Expected" value, the first connector value, AKA "A" value.
=> A/B - UI - Swap columns in the difference table 

quesma/quesma/config/config_v2.go, quesma/quesma/config/config_v2_test.go, quesma/quesma/config/test_configs/has_common_table.yaml, quesma/quesma/config/test_configs/use_common_table_global_property.yaml
This PR adds global `useCommonTable` flag. This flag will be inherited when it's missing in index configuration
=> Adding global useCommonTable property

quesma/quesma/schema_transformer.go, quesma/quesma/search.go
We can remove that `string` specific transformer. We've got a generic solution already.
Before:
Clickhouse on the left. 
After:
Clickhouse on the left.
=> Remove string specific array transfomer

quesma/table_resolver/rules.go, quesma/table_resolver/table_resolver.go, quesma/table_resolver/table_resolver_test.go
This PR changes the way patterns (wildcards such as `logs*`) are handled by `table_resolver`. 
Previously, many `table_resolver` rules had two code paths - one code path for a single index (e.g. `logs1`) and one code path for patterns (e.g. `logs1,logs2` or `logs*`), making those rules more complicated. Moreover, one rule `makeCheckIfPatternMatchesAllConnectors` was the primary one to handle patterns and it contained fragments of other rules.
This PR introduces `patternSplitter`, `decisionMerger`. The `table_resolver` now works like this:
1. `patternSplitter` splits a pattern (e.g. `logs*`) into concrete single indexes (e.g. `logs1`, `logs2`)
2. Existing rules are evaluated on each single index separately
3. `decisionMerger` merges decisions of single indexes, making sure that the …
=> table_resolver refactor - introduce patternSplitter, decisionMerger

ci/it/configs/quesma-with-dual-writes-and-common-table.yml.template, quesma/quesma/config/config_v2.go, quesma/quesma/config/config_v2_test.go, quesma/quesma/config/test_configs/use_common_table_global_property.yaml
This PR moves global `useCommonTable` to processor level (under config) instead of fully global :
```
processors:
- name: my-query-processor
type: quesma-v1-processor-query
config:
```
=> UseCommonTable global per processor

quesma/testdata/clients/clover.go
Add a test with weird names. Tested it also e2e, Clickhouse accepts this query and returns `> 0` rows on my test data.
=> Add 1 test

quesma/stats/errorstats/error_statistics.go
Problem, our dashboard flickers due to undefined order if count is exact:
https://github.com/user-attachments/assets/6b1e5ba3-d219-4b21-b527-adac006dabb6
It looks poorly on demos.
=> Stop flickering of top errors

.github/workflows/integration-tests.yml
A small fix after 7b55f0df6462fdce615a6c81040c9cb50d5e5ec5:
I followed the syntax in the `slack-github-action@v2.0.0` changelog (`<@channel>`), but it's not actually mentioning the `@channel` group. Bring back the old syntax `<!channel>` which should work correctly.
=> Change `<@channel>` to `<!channel>`

quesma/quesma/mux/mux.go
d36b617 changed the logic in `findHandler` when it comes to returning decision: after d36b617, the decision is only filled out if the predicate matched (otherwise it's `nil`).
Previously, the decision would be returned in both scenarios: if predicate matched or if predicate did not match.
d36b617 caused a regression in integration tests: if an index is closed in the configuration, the predicate does not match, but the code still needs a decision (with `IsClosed: true`) to be able to return a correct `index_closed_exception` response. Without a decision (`nil`) it wasn't able to return that expected response.
=> Always return decision in `findHandler`

quesma/quesma/router.go
Elastic client in Python uses the PUT method to perform a bulk request.
=> Add support for PUT /_bulk

quesma/queryparser/aggregation_parser.go, quesma/queryparser/pancake_aggregation_parser.go, quesma/queryparser/pipeline_aggregations.go
Similar to https://github.com/QuesmaOrg/quesma/pull/1006 , but for pipeline aggregations.
I want to simplify and unify interfaces of our parsers, so all of them simply return something like `(aggregation, error)`. Code should be cleaner, and proper returning errors to Kibana much easier.
=> Report errors in queries better #2

quesma/clickhouse/schema_test.go, quesma/clickhouse/table.go, quesma/logger/logger.go, quesma/queryparser/aggregation_parser.go, quesma/queryparser/pancake_sql_query_generation_test.go, quesma/queryparser/query_parser.go
Part of https://github.com/QuesmaOrg/quesma/issues/4
We recently encountered some log spam on customer's panels, so I decided to remove some false positive warnings/errors. Would also like to add warn+ logging to all tests, but even if it's be possible, I'll do that gradually.
This PR eliminates _a lot_ of log spam in our tests (vast majority of it).
=> Remove false positive errors from logs #1

ci/it/configs/quesma-with-dual-writes-and-common-table.yml.template, ci/it/testcases/test_dual_write_and_common_table.go, quesma/quesma/functionality/resolve/resolve.go, quesma/quesma/functionality/resolve/resolve_test.go
I guess this is due to some historical reasons which are no longer accurate. 
After this patch, you can create data stream with ES index without issues:
At this moment, we simply return all(*) the sources. After all, created data view may outlive Quesma and related routing configuration.
(*) all the Elasticsearch indices/datastreams/aliases matching desired pattern plus our ClickHouse tables presented as Data Streams.
Closes: https://github.com/QuesmaOrg/quesma/issues/996
=> Don't remove Elasticsarch indices/datastreams from `_resolve` endpoint

ci/it/configs/quesma-ingest.yml.template, ci/it/integration_test.go, ci/it/testcases/base.go, ci/it/testcases/test_ingest.go, quesma/ingest/parser.go
When a `geo_point` field is added to `fieldEncodings`, actually two fields get added:
- `my_field.lat`
- `my_field.lon`
`SchemaToColumns` however tried to find `my_field` in `fieldEncodings` (which was missing; only `my_field.lat` and `my_field.lon` were there). This resulted in creating (incorrect, unused) columns `lat`, `lon` since `internalPropertyName` was empty.
Fix the problem by accessing `my_field.lat` and `my_field.lon` keys in `fieldEncodings` instead (which should be there).
Add new integration test that checks Quesma's ingest of Kibana sample flights, Kibana sample ecommerce. The tests without "PUT mapping" caught the fixed issue (this is how I found it).
=> Fix `SchemaToColumns` for `geo_point` types, add ingest integration tests

ci/it/configs/quesma-ingest.yml.template, ci/it/testcases/test_ingest.go, quesma/ingest/insert_test.go, quesma/ingest/parser.go, quesma/ingest/processor.go, quesma/ingest/processor_test.go
Before this change, the ingest logic looked roughly like this:
1. Initial transformation of JSON ("pre ingest transformer", field encodings, ...)
2. Generating CH table schema based on JSON + config (for "CREATE TABLE" or "ALTER TABLE"s)
3. Transformation of JSON (transformer object: flattening map and removing ignored fields)
4. Executing SQL query with the JSON data (after both initial and second transformation)
The issue with this logic is that the transformation (step 3) removes ignored fields, but the step 2 operated on a JSON with those fields present.
Rather than introducing additional logic to step 2 to handle ignored fields, this PR takes another approach: it moves the step 3 before the step 2. This way the CREATE TABLE/ALTER TABLE statements don't take into account the ignored …
=> Move ingest transformer earlier in the process

quesma/model/bucket_aggregations/date_histogram.go, quesma/queryparser/dates.go, quesma/queryparser/dates_test.go, quesma/queryparser/pancake_aggregation_parser_buckets.go, quesma/queryparser/query_parser.go, quesma/util/intervals.go, quesma/util/intervals_test.go
I noticed this module depends on `quesma/clickhouse`, which stroke me as little odd when I realized that this is just one util function and part of parsing (specifically date parsing) which naturally belongs there. 
Related: https://github.com/QuesmaOrg/quesma/issues/1017
=> Remove `quesma/kibana`

quesma/elasticsearch/client.go, quesma/util/utils.go
Little hackish, as it involves additional call to the backend (in order to decide whether use OpenSearch or Elasticsearch security endpoint) **but** given that we have auth header cache I think we might get away with that 😉 
FWIW,  Elasticsearch 7 uses the same [endpoint (`_security/_authenticate`)](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-authenticate.html) as Elasticsearch 8 for auth (just verified :relieved:)
=> Support auth against OpenSearch

quesma/telemetry/phone_home.go
Our telemetry collector should ignore SSL certificate validation and just collect the Elasticsearch vitals.
=> `phone_home` - ignore SSL certificate when calling Elasticsearch

quesma/main.go, quesma/quesma/ui/console_routes.go
This PR adds extra `pprof` endpoints that we can handle. 
So we can profile: 
```
go tool pprof -http=: http://localhost:9999/debug/pprof/profile
go tool pprof -http=: http://localhost:9999/debug/pprof/heap
go tool pprof -http=: http://localhost:9999/debug/pprof/mutex
go tool pprof -http=: http://localhost:9999/debug/pprof/block
```
=> Extra `pprof` endpoints

quesma/table_resolver/table_resolver.go
This is a result of mutex profiling:
Yes, we should keep our critical section as small  as possible
=> More granular locking

quesma/health/elastic.go
When backend cluster's SSL setup wasn't printine, we've been showing `Failed` status in the UI, even though everything was working just fine.
Fixed by reusing our existing Elasticsearch client, which also cleaned up the code a little.
=> Fix adminconsole's Elasticsearch status

docs/public/docs/limitations.md
Update limitations.md:
- Update the list of supported endpoints
- Update the list of supported ElasticSearch/ClickHouse types
=> Update limitations: supported endpoints and supported types

ci/it/configs/quesma-ingest.yml.template, ci/it/testcases/base.go, ci/it/testcases/test_ingest.go, quesma/ingest/insert_test.go, quesma/ingest/parser.go
In the `CREATE TABLE`, Quesma includes fields we got from `PUT /:index/_mapping` (but are missing from the JSON). This code path incorrectly computed field encodings - used the encoded field name in the comment instead of the field name before encoding.
Fix the issue by using the `reverseMap` (field name before encoding) in that code path.
Fixes #1045
=> Fix incorrect field encodings for fields from mappings (but missing from JSON)

quesma/main.go, quesma/quesma/dual_write_proxy_v2.go, quesma/quesma/elastic_http_frontend_connector.go
This PR:
- introduces `ElasticHttpFrontendConnector` and integrate with the existing routing implementation.
- extracts `elasticFallback` function
=> Using new http frontend connector API

quesma/frontend_connectors/decision.go, quesma/ingest/common_table_test.go, quesma/ingest/ingest_validator_test.go, quesma/ingest/insert_test.go, quesma/ingest/processor.go, quesma/quesma/dual_write_proxy.go, quesma/quesma/dual_write_proxy_v2.go, quesma/quesma/functionality/bulk/bulk.go, quesma/quesma/matchers.go, quesma/quesma/mux/mux.go, quesma/quesma/router.go, quesma/quesma/router_test.go, quesma/quesma/router_v2.go, quesma/quesma/search.go, quesma/quesma/search_ab_testing.go, quesma/quesma/search_common_table_test.go, quesma/table_resolver/empty.go, quesma/table_resolver/model.go, quesma/table_resolver/rules.go, quesma/table_resolver/table_resolver.go, quesma/table_resolver/table_resolver_test.go
This is prerequisite for moving `mux.PathRouter` to `frontend_connectors` and integrate it with the new API
=> Moving Decision to frontend_connectors

quesma/frontend_connectors/elasticsearch_ingest.go, quesma/main.go, quesma/processors/base_processor.go, quesma/processors/es_to_ch_ingest/elasticsearch_to_clickhouse_ingest_processor.go, quesma/v2/core/quesma_apis.go, quesma/v2/core/quesma_builder.go
Two things:
* Temporarily remove embedding of `BasicHTTPFrontendConnector` which caused issues
* Adds `Init()` function to processor where one can perform actions **after** processor has been fully set up - has all the connectors, etc.
=> Initialize processors

quesma/frontend_connectors/basic_http_frontend_connector.go, quesma/frontend_connectors/elasticsearch_ingest.go, quesma/frontend_connectors/router_v2.go, quesma/main_test.go, quesma/quesma/dual_write_proxy.go, quesma/quesma/router.go, quesma/v2/core/dispatch.go, quesma/v2/core/mux.go, quesma/v2/core/quesma_apis.go, quesma/v2_test_objects.go
This PR unifies `HTTPFrontendHandler`. Now `POC router` and v1 `PathRouter` uses the same handler signature:
```
type HTTPFrontendHandler func(ctx context.Context, req *Request) (*Result, error)
```
=> Unifying HTTPFrontendHandler

quesma/quesma/schema_transformer.go, quesma/quesma/schema_transformer_test.go
Our queries fail if we try to do `sum` or `avg`  over a string or date column. This PR detects and compensates (adds a hack) it.
=> Fix Avg/Sum over Datetime column

.github/workflows/generate-notice.yml
We are in the process of an internal code refactor and we have introduced a new module `quesma_v2` for this refactor.
Unfortunately, the `go-licence-detector` (generating `NOTICE.MD`) tries to find a licence for `quesma_v2` module and it fails.
We could inform it that `quesma_v2` is licensed under "Elastic-2.0", however that licence is not allowed in the default `go-licence-detector` configuration. I wasn't sure if we should allow "Elastic-2.0" dependencies generally, therefore this change works around this issue by just filtering out `quesma_v2` from dependency list.
=> Fix NOTICE.MD generator for quesma_v2 "dependency"

quesma/frontend_connectors/basic_http_frontend_connector.go, quesma/frontend_connectors/router_v2.go, quesma/main.go, quesma/v2/core/mux.go
This PR implements first step of integration, it calls `router.Matches` from request handler as in v1 version
=> Integrate v1 reroute logic with v2 APIs

quesma/clickhouse/quesma_communicator.go, quesma/model/expr_string_renderer.go, quesma/optimize/pipeline.go, quesma/optimize/split_time_range.go, quesma/quesma/config/config_v2.go, quesma/quesma/schema_transformer.go, quesma/quesma/schema_transformer_test.go, quesma/quesma/search.go, quesma/testdata/full_search_requests.go, quesma/testdata/requests.go
Context: We noticed that for some schemas (that don't ORDER BY time), the "Discover" view in Kibana over long time ranges can be very slow, even though it only shows 500 results. Changing the time range to a shorter one can make the query faster. (See this issue in ClickHouse for a similar example: https://github.com/ClickHouse/ClickHouse/issues/69315)
This optimization therefore splits the time range into parts: a short time range, on which we bet that the query will be fast (and still return LIMIT many results) and a long time range, which will be used to get the rest of the results (in case the short time range didn't return enough results). The ranges are customizable (potentially even more than 2).
During the development I also fixed two related problems:
- added …
=> Add split_time_range optimizer

quesma/queryparser/aggregation_parser.go, quesma/queryparser/aggregation_parser_new_logic_test.go, quesma/queryparser/pancake_sql_query_generation_test.go, quesma/queryparser/query_parser.go, quesma/queryparser/query_parser_range_test.go, quesma/queryparser/query_parser_test.go, quesma/queryparser/query_translator.go, quesma/queryparser/query_translator_test.go, quesma/quesma/functionality/terms_enum/terms_enum.go, quesma/quesma/functionality/terms_enum/terms_enum_test.go, quesma/quesma/highlight_test.go, quesma/quesma/query_translator.go, quesma/quesma/search_opensearch_test.go
This instance is not really needed, `HandleTermsEnum` was the only place where this has been used.
The biggest change is probably `terms_enum.go` and also the `ResolveField(cw.Ctx, fieldStr, cw.Schema)` - it's no longer a method, but function taking Schema as an argument.
=> Remove `clickhouse.LogManager` from `ClickhouseQueryTranslator`

quesma/frontend_connectors/basic_http_frontend_connector.go, quesma/quesma/dual_write_proxy_v2.go
This PR deletes orphaned (not used) router and move this functionality to `BasicHTTPFrontendConnector` where it should be.
=> Moving FailedRequestsCollector call into BasicHTTPFrontendConnector

bin/build-image.sh
Without the `DOCKER_BUILDKIT` environment variable the image fails to build on Linux (note: this doesn't affect CI because CI doesn't use this helper script).
=> Fix `bin/build-image.sh` on Linux

ci/it/testcases/utils.go
The integration tests rare flakiness (~1/16 chance) seems to have multiple causes. This PR fixes one of them - flakiness caused by port conflicts between IPv4 and IPv6.
In one of the flaky runs, `QueryAndIngestPipelineTestcase.testWildcardGoesToElastic` panicked while trying to parse results returned from Quesma (Quesma seemingly returned something really incorrect!):
```go
resp, bodyBytes := a.RequestToQuesma(ctx, t, "POST", "/unmentioned_index/_search", []byte(`{"query": {"match_all": {}}}`))
var jsonResponse map[string]interface{}
if err := json.Unmarshal(bodyBytes, &jsonResponse); err != nil {
t.Fatalf("Failed to unmarshal response body: %s", err)
}
hits, _ := jsonResponse["hits"].(map[string]interface{}) // PANIC HERE
```
Thankfully I collected a tcpdump from this run, which showed …
=> Fix one of the causes of IT flakiness: port conflicts between IPv4 and IPv6

ci/it/integration_test.go, ci/it/testcases/base.go, ci/it/testcases/test_ab.go, ci/it/testcases/test_dual_write_and_common_table.go, ci/it/testcases/test_ingest.go, ci/it/testcases/test_reading_clickhouse_tables.go, ci/it/testcases/test_transparent_proxy.go, ci/it/testcases/test_two_pipelines.go, ci/it/testcases/test_wildcard_clickhouse.go, ci/it/testcases/test_wildcard_disabled.go, ci/it/testcases/utils.go
We see (relatively rarely) integration tests being flaky. In those cases of flakiness the current logging is not sufficient to really understand the cause of the problem.
This PR aims to improve logging by printing logs of all containers when a test fails.
`printContainerLogs` is added to `Containers.Cleanup()` code to print the logs of containers.
Additionally, the `Cleanup()` function is now **always** called, even if the containers failed to start or tests failed. To make sure it can print some logs:
- the code now has less panics, which would have prevented `Cleanup()` from running
- in `setupClickHouse()` and others we return the container object in case container failed to start instead of `nil` (but still with error) to be able to recover some logs
- if one container fails to …
=> Print container logs when integration test fails

ci/it/configs/quesma-ab.yml.template, ci/it/configs/quesma-as-transparent-proxy.yml.template, ci/it/configs/quesma-ingest.yml.template, ci/it/configs/quesma-now-reads-clickhouse-tables.yml.template, ci/it/configs/quesma-wildcard-clickhouse.yml.template, ci/it/configs/quesma-wildcard-disabled.yml.template, ci/it/configs/quesma-with-dual-writes-and-common-table.yml.template, ci/it/configs/quesma-with-two-pipelines.yml.template, ci/it/go.mod, ci/it/go.sum, ci/it/integration_test.go
- Bump go to 1.23.2 in `ci/it` to be in line with go version in other modules in the repo
- Update `golang.org/x/net` to v0.33.0 to get rid of the "Security advisory" warning (https://github.com/QuesmaOrg/quesma/security/dependabot/6)
- Turn on SQL tracing in ITs
- Use `testing.T.Cleanup()` instead of `defer` - `testing.T.Cleanup()` will run even if a test panics/fails/timeouts
=> A couple small fixes to ITs

quesma/frontend_connectors/basic_http_frontend_connector.go, quesma/main.go, quesma/main_test.go, quesma/quesma/auth_middleware.go, quesma/quesma/dual_write_proxy_v2.go, quesma/v2/core/quesma_apis.go
This PR adds a new API call for registering middlewares into the HTTP FrontendConnector.
=> Adding middleware handling API

quesma/logger/log_with_throttling.go, quesma/model/base_visitor.go, quesma/model/expr.go, quesma/model/expr_string_renderer.go, quesma/model/simple_query.go, quesma/queryparser/query_parser.go, quesma/queryparser/query_parser_test.go, quesma/testdata/requests.go
By accident I noticed our SQL generated for `ids` looks quite nonsensical, e.g. that's what's generated for my new very simple request:
```
WHERE "@timestamp" IN toDateTime64('2024-12-21 07:29:03.367', '2024-12-21 07:29:02.992', 3)
```
Also noticed we have 0 tests for this query. Fixing those 2 things here.
(adding `TupleExpr` for just this 1 usecase might seem unnecessary, but it's needed in my 2 other open PRs, so I'd do that)
Also, minor: changed `return model.NewSimpleQuery(nil, false)` to more descriptive `return model.NewSimpleQueryInvalid()` everywhere.
=> Fix `ids` query DSL

quesma/main.go, quesma/quesma/dual_write_proxy_v2.go, quesma/v2/core/mux.go
This PR:
-  for the first time utilize quesma v2 lifecycle APIs (start/stop) without using ad hoc http server.
The same thing we have to do for TCP frontend connector. Finally, we should have one `quesmaV2` object at 
`constructQuesma` level.
- fixes some issues with updating mapping handlers
=> Utilizing quesma v2 lifecycle api

quesma/frontend_connectors/elastic_http_frontend_connector.go, quesma/main.go, quesma/quesma/dual_write_proxy_v2.go
This PR just moves `ElasticHTTPFrontendConnectors` to the right package (`frontend_connectors`)
=> Moving elastic-http-frontend-connector to frontend_connectors package

quesma/main_test.go, quesma/processors/ab_test_processor.go, quesma/test_utils.go, quesma/v2_test_objects.go
This PR refactors v2 object graph structure unit tests in order to check expected responses.
=> v2 unit tests refactoring, validate responses

quesma/model/bucket_aggregations/terms.go, quesma/model/expr.go, quesma/model/expr_string_renderer.go, quesma/queryparser/pancake_aggregation_parser_buckets.go, quesma/queryparser/pancake_sql_query_generation_test.go, quesma/queryparser/query_parser.go, quesma/testdata/aggregation_requests_2.go, quesma/util/regex/regex.go
https://github.com/QuesmaOrg/quesma/issues/1085
TODO (next PRs):
* `include` parameter can probably be quite easily handled the same way
* our regex translator is pretty basic, it requires tests + possibly a better implementation
Issue from the issue works fine now:
=> `Terms`: start supporting `exclude` param

quesma/model/bucket_aggregations/terms.go, quesma/model/pipeline_aggregations/common.go, quesma/model/pipeline_aggregations/max_bucket.go, quesma/model/pipeline_aggregations/sum_bucket.go, quesma/model/query_result.go, quesma/queryparser/pancake_sql_query_generation_test.go, quesma/testdata/aggregation_requests_2.go, quesma/testdata/kibana-visualize/aggregation_requests.go, quesma/testdata/opensearch-visualize/pipeline_aggregation_requests.go, quesma/util/utils.go
Response for a `bool` bucket needs to be slightly different.
Before:
After:
=> Quickfix: `bool` column with `terms` aggr

quesma/quesma/config/config_v2.go
Ingest statistics were enabled by default. If we have a lot of indexes, these stats can lead to OOM. This PR fixes configuration parsing. Ingest statistics are disabled by default now.
=> Respect `ingestStatistics` config parameter

quesma/ingest/processor.go, quesma/ingest/processor2.go, quesma/quesma/config/config.go, quesma/quesma/config/config_v2.go, quesma/quesma/config/config_v2_test.go, quesma/quesma/config/test_configs/ingest_only_optimizers.yaml
This PR adds the ability to buffer inserts. If the optimizer is enabled, we add an "async insert"[1] setting to every `INSERT` query. 
Motivation: clickhouse doesn't handle multiple inserts per second well.  We need to compensate for this.
The optimizer can be enabled for all indexes 
```
...
...
'*':
optimizers:
- async_insert:
disabled: false
properties:
wait_for_async_insert: 0 
async_insert_busy_timeout_ms: 10000
...
```
Or can be added to a single index.
```
...
device_logs:
optimizers:
- async_insert:
disabled: true
other:
optimizers:
- async_insert:
disabled: false
...
```
[1] https://clickhouse.com/blog/asynchronous-data-inserts-in-clickhouse
=> Async Insert Optimizer

quesma/elasticsearch/index.go, quesma/elasticsearch/index_test.go, quesma/end_user_errors/clickhouse.go, quesma/end_user_errors/end_user.go, quesma/ingest/processor.go, quesma/quesma/router.go, quesma/quesma/router_v2.go, quesma/util/utils.go
ClickHouse stores column data in files, with each file’s name being a combination of the table name and the column name. We should not exceed the maximum path length. Elasticsearch limits the index name to 256 characters, and this pull request (PR) applies that limit.
@pdelewski  please review this PR. Not sure how we should handle the field limit.
=> Limit index  name length

quesma/clickhouse/clickhouse.go, quesma/quesma/functionality/terms_enum/terms_enum.go, quesma/quesma/route_handlers.go, quesma/quesma/router.go, quesma/quesma/router_v2.go
Mainly that's just adding 2 more methods to `LogManagerIFace` so that `terms_enum` request can be handled using `v2` api as well.
Another round of "general changes" helpful for https://github.com/QuesmaOrg/quesma/pull/1119
=> More router_v2 portability (terms_enum + minor additions)

quesma/ingest/processor.go, quesma/ingest/processor2.go
We should enable async_insert (#1151) by default. The default settings have been slightly changed to be more safe.
=> Enable async_insert optimizer by default

quesma/clickhouse/clickhouse.go, quesma/eql/query_translator.go, quesma/quesma/query_translator.go, quesma/quesma/search.go, quesma/table_resolver/table_resolver_dummy.go
Changing the QueryRunner so that it relies on `clickhouse.LogManagerIFace` instead of `*clickhouse.LogManager`.
Having that, we won't need a duplicate of `QueryRunner` in https://github.com/QuesmaOrg/quesma/pull/1119. 
Caveat: we're adding a that dumb dummy table resolver, but that's way simpler than having a copy of QueryRunner. 
Lots of LoCs to save here 😉
=> Get rid of additional QueryRunner

quesma/backend_connectors/clickhouse_backend_connector.go, quesma/backend_connectors/elasticsearch_backend_connector.go, quesma/backend_connectors/mysql_backend_connector.go, quesma/backend_connectors/postgres_backend_connector.go, quesma/clickhouse/clickhouse.go, quesma/clickhouse/connection.go, quesma/clickhouse/quesma_communicator.go, quesma/clickhouse/table_discovery.go, quesma/common_table/const.go, quesma/connectors/connector.go, quesma/ingest/common_table_test.go, quesma/ingest/ingest_validator_test.go, quesma/ingest/insert_test.go, quesma/ingest/processor.go, quesma/quesma/functionality/terms_enum/terms_enum_test.go, quesma/quesma/search.go, quesma/quesma/search_common_table_test.go, quesma/quesma/search_norace_test.go, quesma/quesma/search_opensearch_test.go, quesma/quesma/search_test.go, quesma/quesma/ui/ab_testing.go, quesma/telemetry/phone_home.go, quesma/v2/core/backend_connectors.go, quesma/v2/core/quesma_apis.go
... so that it relies on `quesma_api.BackendConnector` instead of `*sql.DB`.
This may look like it's complicating the current codebase, but effectively makes both of these structures reusable in the v2 API.
Ref: https://github.com/QuesmaOrg/quesma/pull/1119
=> Generalize `TableResolver` and `LogManager` implementation

quesma/quesma/functionality/field_capabilities/field_caps.go, quesma/quesma/search.go
We can speed up the process of resolving multiple schemas more simply.  No cache is required now.
=> Multiple schema resolve - speed up 

quesma/backend_connectors/basic_sql_backend_connector.go, quesma/backend_connectors/clickhouse_backend_connector.go, quesma/backend_connectors/mysql_backend_connector.go, quesma/backend_connectors/postgres_backend_connector.go, quesma/go.mod, quesma/go.sum
A lot of golang drivers for different SQL libraries expose a standard `sql.DB` interface. Our backend connector code for ClickHouse, Postgres, MySQL can be unified around this interface.
This reduces the code duplication by moving the common code to a new `basic_sql_backend_connector` struct.
=> Introduce `basic_sql_backend_connector` for `sql.DB` connectors

quesma/queryparser/query_parser_test.go, quesma/queryparser/query_translator.go, quesma/quesma/query_translator.go, quesma/quesma/search.go, quesma/quesma/search_opensearch_test.go
Removes `*config.QuesmaConfiguration` from `query_translator.go` which has not been used anyways.
=> Remove `*config.QuesmaConfiguration` from `query_translator.go`

ci/it/testcases/test_ingest_types.go
We saw some flakiness in this test, let's print the entire received response from Quesma to make it easier to understand the issue.
=> Print full Quesma response in `test_ingest_types` integration test

quesma/quesma/l4_proxy.go, quesma/quesma/l4_proxy_test.go, quesma/quesma/quesma.go
Moving `l4_proxy` package (two files) to quesma
=> Get rid of l4_proxy package

quesma/ab_testing/collector/collector.go, quesma/ab_testing/collector/fanout.go, quesma/ab_testing/sender/coordinator.go, quesma/backend_connectors/elasticsearch_backend_connector.go, quesma/elasticsearch/index_resolver.go, quesma/main.go, quesma/processors/es_to_ch_common/common.go, quesma/processors/es_to_ch_ingest/elasticsearch_to_clickhouse_ingest_processor.go, quesma/processors/es_to_ch_query/elasticsearch_to_clickhouse_query_processor.go, quesma/quesma/dual_write_proxy_v2.go, quesma/quesma/functionality/bulk/bulk_test.go, quesma/quesma/functionality/terms_enum/terms_enum_test.go, quesma/quesma/quesma.go, quesma/quesma/router_test.go, quesma/quesma/search.go, quesma/quesma/search_common_table_test.go, quesma/quesma/ui/data_sources.go, quesma/quesma/ui/html_pages_test.go, quesma/quesma/ui/management_console.go, quesma/table_resolver/table_resolver_dummy.go, quesma/v2_quesma_builder.go
I've made some (a lot of) shortcuts to merge v2 architecture processors. Now it's time to take the high road.
Changes:
* added common table support for query/ingest
* Removed dependency on `IndexManagement` (the only component which depends on it is `TableResolver`
* Switching AB testing logs collector to Elasticsearch to remove dependency on `ClickHouse Ingester` interface @nablaone
=> Re-adding features to V2 architecture

quesma/quesma/config/config_v2.go
We still use `Override` internally, however in config there is `tableName`
```
processors:
- name: my-query-processor
type: quesma-v1-processor-query
config:
indexes:
kibana_sample_data_ecommerce:
tableName: "kibana_sample_data_ecommerce_ext"
```
This PR updates property name according to configuration and documentation
=> Fixing error message to avoid user confusion

ci/it/testcases/test_ab.go, quesma/ab_testing/collector/collector.go, quesma/ab_testing/sender/coordinator.go, quesma/main.go, quesma/processors/es_to_ch_common/common.go, quesma/processors/es_to_ch_ingest/elasticsearch_to_clickhouse_ingest_processor.go
I decided to revert this change and make it work in V2 architecture. 
Little nonsense in the dependencies, but at the cost of 100% feature parity 🙃
=> Bring back ingest ab result to CH

quesma/frontend_connectors/basic_http_frontend_connector.go, quesma/frontend_connectors/dispatcher.go, quesma/frontend_connectors/elastic_http_frontend_connector.go
Currently, we have two `router_v2.go` files, which is very confusing:
- one is member of `frontend_connector` package and is responsible for dispatching
- second is a member of `quesma` package and contains logic for `http` routing definition
This PR updates the first one.
=> Refactoring : changing routerV2 to dispatcher

ci/it/testcases/test_transparent_proxy.go, ci/it/testcases/test_wildcard_clickhouse.go, ci/it/testcases/test_wildcard_disabled.go, quesma/elasticsearch/index.go, quesma/frontend_connectors/elasticsearch_query.go, quesma/quesma/router_test.go, quesma/quesma/router_v2.go
In ElasticSearch there's a `GET /:index` endpoint. Quesma supports that endpoint, however a `GET /_license` request erroneously matched to that endpoint, routing it into ClickHouse instead of a fallback to ElasticSearch.
Previously a couple similar endpoints (such as `/_nodes`, `/_xpack`, `/_stats`) were hardcoded to be routed to Elastic, however that list was not exhaustive and was prone to become obsolete if Elastic introduced a new endpoint.
This PR changes the routing logic - now if an index name starts with `_` (forbidden index name in Elastic and indicative of an endpoint name) it is assumed that it is an internal path and should be routed to Elastic.
=> Fix misrouting of `/_license` (and others) to ClickHouse

quesma/backend_connectors/tcp_backend_connector.go, quesma/frontend_connectors/basic_tcp_connector.go, quesma/frontend_connectors/tcp_mysql_connection_handler.go, quesma/main.go, quesma/processors/tcp_passthrough_mysql_processor.go, quesma/v2/core/backend_connectors.go
This PR adds a new processor and frontend/backend connectors that allows Quesma to act as a MySQL proxy.
Added components:
- `TcpMysqlConnectionHandler` - splits incoming TCP stream into MySQL wire protocol packets
- `TcpPassthroughMysqlProcessor` - reads incoming MySQL packets, forwards them to a real MySQL server (via `TcpBackendConnector`) and forwards back any responses from the real MySQL server to the connected client.
- `TcpBackendConnector` - a raw TCP connection to some server (in this case MySQL server)
This is a very early experimental version. In particular it has (at least) these limitations:
- No support for encrypted MySQL traffic
- Manually parses MySQL packets - we should probably use Vitess for that
- Stores the connection inside metadata, not some `Session` abstraction …
=> Add (TCP) passthrough MySQL processor

quesma/clickhouse/table_discovery.go, quesma/frontend_connectors/dispatcher.go
Before this change such configuration:
```
kibana_sample_data_flights:
tableName: "kibana_sample_data_flights_ext"
```
required also explicit override index definition:
```
kibana_sample_data_flights_ext:
```
otherwise kibana_sample_data_flights_ext was treaded as non-configured.
=> Relaxing explicit index definition override requirement

quesma/quesma/es_responses.go, quesma/quesma/matchers.go, quesma/quesma/router_test.go, quesma/quesma/router_v2.go
Given that we have the sophisticated bulk body introduced in https://github.com/QuesmaOrg/quesma/pull/1202, there is no longer need to examine the bulk payload in order to see where it should be routed. 
Also, that `matchedAgainstBulkBody` implementation wasn't entirely correct anyways (relying on optional data line being always %2).
=> Fix `_bulk` endpoint

quesma/ingest/ingest_validator.go, quesma/ingest/ingest_validator_test.go
Before this change, `validateValueAgainstType` would just compare the type name string in case of arrays. This could cause problems in case of arrays of numbers, for example if the user had an `Array(Float64)` ClickHouse column, but tried to insert an array of ints (e.g. `[3, 5, 7]`).
After this fix, the `validateValueAgainstType` logic now works recursively, validating the element type of `Array` (e.g. `Float64` of `Array(Float64)`) and comparing that with an element of incoming array from Elastic API.
=> Improve validation of Array types

quesma/clickhouse/parser.go, quesma/clickhouse/schema.go, quesma/ingest/parser.go, quesma/ingest/processor.go
Before this change, `NewType(nil)` would return a unhelpful error message:
```
Unsupported type '<nil>' of value: <nil> in /quesma/clickhouse/schema.go:273
```
Improve the log by providing the "origin" of the `nil` value (in most cases the column name with that `nil` value).
=> Improve logging of NewType

.github/workflows/release.yml
By the time we figure that out programmatically, let's just add a placeholder to remind about adding at least one sentence about what is changing.
=> Add placeholder for release notes

quesma/quesma/router_v2.go, quesma/quesma/search.go
This PR puts a tiny improvement over multi-search handling: 
❗ `:index/_msearch` calls targeted to Elasticsearch will be routed directly to Elasticsearch instead of failing later on with enigmatic `no clickhouse connector` error.
Implementing a high-road fix in the current architecture requires adding a somehow 'dirty' dependency (QueryRunner will have to call Elasticsearch directly). Overall we can do it and sanitize `handleSearchCommon` a little too, but together with @pdelewski we decided to postpone this for now.
=> Improve `_msearch` handling

quesma/quesma/search_test.go, quesma/testdata/aggregation_requests.go
I run e2e twice now and no errors. It failed because of:
* data race with logger in the test
* sometimes flaky 1 aggregation test, mistype and it had `15` and `25` in 2 places, where the number must be the same (result of the same query)
Sorry for the issue, my PR a few days ago introduced the first error.
=> Quickfix failing e2e

ci/it/configs/quesma-ingest.yml.template, ci/it/testcases/test_ingest.go, quesma/clickhouse/parser.go, quesma/clickhouse/schema.go, quesma/ingest/parser.go, quesma/ingest/processor.go
When a user sends a JSON with a `nil` field, we can't determine a ClickHouse type for such field (column). This is the case for `nil` (we used to fall back to String), an empty array or empty dictionary.
This PR changes the logic in `NewType()` - when the type is determined to be invalid/incomplete, the function now returns an error. The `CREATE TABLE` code now can skip such problematic column. If a user sends such field with complete type, it will be handled in some future `ALTER TABLE ADD COLUMN` statement (as now Quesma sees an example with complete type).
=> Skip invalid/incomplete types in CREATE TABLE

.github/go-licence-detector/rules.json, .github/workflows/generate-notice.yml
After #1212, go-licence-detector GitHub Actions job started failing. One of the added dependencies uses [Unlicense](https://en.wikipedia.org/wiki/Unlicense) license, which is not on the allowlist of the default go-licence-detector rules list.
Unlicense is a public-domain-equivalent license. The default rules list already allowed similar licenses, such as "CC0-1.0" and "Public Domain", so it should be OK for us to add Unlicense to the allowed list.
The added rules.json is a default rules file with only Unlicense added.
This fixes the NOTICE.MD generation with go-licence-detector.
=> Add Unlicence to allowed license list for go-licence-detector

quesma/logger/logger.go, quesma/v2/core/quesma_logger.go
This is a first PR in a series to reduce amount of logs generated by Quesma. This PR rate limits logs globally for entire Quesma. This is meant as a fail-safe in case some codepath generates too much logs (specific codepaths will be fixed in next PRs).
The rate limits in this PR are generous, as it's only a fail-safe:
- ~100k log lines per hour
- Allow for bursts of 600 lines of logs (per 20 second period)
- When the limit is exhausted (for the 20 second period), logger will cut down on amount of logs, printing 1/100th of logs. This shedding is not an elegant solution, but that way the user sees that Quesma is still running and printing something (until the next 20 second period).
=> Rate limit logs globally

ci/it/testcases/test_ingest.go, quesma/clickhouse/schema.go, quesma/ingest/ingest_validator.go, quesma/ingest/ingest_validator_test.go
In the ingest processor we had two separate codepaths for converting a Golang type into ClickHouse column type: one used in `CREATE TABLE` codepath (`clickhouse.NewType`) and another in ingest validation (`getTypeName`). The first one had better support for (nested) arrays and maps, which were not fully supported in ingest validation.
Therefore this PR unifies the ingest validation codepath to use the `clickhouse.NewType` from `CREATE TABLE` codepath. As a result, ingest validation now has a better support for nested arrays, maps (see `test_ingest.go`) and the code is now simpler.
=> Unify golang type to ClickHouse type conversion in `CREATE TABLE` and validation codepaths, improve `Tuple(...)` validation

quesma/clickhouse/schema.go, quesma/go.mod, quesma/go.sum, quesma/logger/logger.go, quesma/quesma/functionality/bulk/bulk.go, quesma/v2/core/quesma_logger.go, quesma/v2/core/quesma_logger_test.go
This PR introduces `logger.DeduplicatedWarn()` and `logger.DeduplicatedInfo()` methods to `quesma_logger`, which automatically deduplicate log messages.
For example,
```
Ingesting via _bulk API, batch size=2 lines
```
is a log line that the code tries to print very often, but with `DeduplicatedInfo()` that exact log line is only printed once. An expirable LRU cache is used with 1 minute expiry time, so the log line is still printed occasionally, but at most 1 every minute.
Additionally, a couple places that produced a lot of logs were migrated to use `DeduplicatedWarn()`/`DeduplicatedInfo()`.
=> Add deduplicated log line printing to quesma_logger, use it in places that logged most often

docs/public/docs/config-primer.md, docs/public/docs/limitations.md, quesma/clickhouse/clickhouse.go, quesma/clickhouse/parserCreateTable.go, quesma/clickhouse/schema.go, quesma/clickhouse/table.go, quesma/clickhouse/table_discovery.go, quesma/common_table/const.go, quesma/ingest/parserCreateTable_test.go, quesma/ingest/processor.go, quesma/main.go, quesma/quesma/config/config.go, quesma/quesma/config/config_v2.go
This PR adds support for `ON CLUSTER` clause within DDL statements. If user want to synchronize DDL across nodes, it is required to place `clusterName` in the ingest processor configuration like this:
```yaml
- name: my-ingest-processor
type: quesma-v1-processor-ingest
config:
clusterName: "quesma_cluster"
indexes:
example:
```
Having that, Quesma is going to append `ON CLUSTER "quesma_cluster"` to all `CREATE TABLE` and `ALTER TABLE` statements.
**Step 0.** Make sure you configured `clusterName` for table named `try_it`.
Test table creation:
```
curl -i -X POST "http://localhost:8080/_bulk" -H "Content-Type: application/ndjson" -d '
{ "index": { "_index": "try_it", "_id": "1" } }
{ "name": "Alice", "age": 30, "city": "New York" }
{ "index": { …
```
=> Adding support for `ON CLUSTER` clause in DDL statements

docs/public/package-lock.json
Update docs JavaScript packages by running `npm update`, in order to fix the "Security" warning:
Our docs after the update render and work correctly.
=> Update docs JS packages

quesma/processors/es_to_ch_ingest/elasticsearch_to_clickhouse_ingest_processor.go, quesma/processors/es_to_ch_query/elasticsearch_to_clickhouse_query_processor.go, quesma/quesma/search.go, quesma/util/utils.go
This is a very basic support for `_msearch` targeting Elasticsearch, not ClickHouse.
The main goal is to provide better Grafana experience which almost exclusively relies on `_msearch` endpoint.
In the future we might expand on this, do a bigger refactor or support parrallel execution of multi search queries.
=> Support `_msearch` queries targetting mixed sources

quesma/clickhouse/schema.go, quesma/ingest/parser.go, quesma/ingest/parser_test.go
This is an invalid ClickHouse type which can end up with:
```
error executing query: code: 43, message: Nested type Tuple(id Nullable(Int64), ns Nullable(Int64)) cannot be inside Nullable type
```
Tuples, similarly to Arrays, cannot be wrapped in a `Nullable` type. This PR fixes this behavior and adds relevant test.
=> Fix creating `Nullable(Tuple)` type

quesma/frontend_connectors/es_responses.go, quesma/frontend_connectors/matchers.go, quesma/frontend_connectors/matchers_test.go, quesma/frontend_connectors/query_translator.go, quesma/frontend_connectors/route_handlers.go, quesma/frontend_connectors/router_test.go, quesma/frontend_connectors/router_v2.go, quesma/frontend_connectors/schema_array_transformer.go, quesma/frontend_connectors/schema_map_transformation.go, quesma/frontend_connectors/schema_search_after_transformer.go, quesma/frontend_connectors/schema_search_after_transformer_test.go, quesma/frontend_connectors/schema_transformer.go, quesma/frontend_connectors/schema_transformer_test.go, quesma/frontend_connectors/search.go, quesma/frontend_connectors/search_ab_testing.go, quesma/frontend_connectors/search_common_table_test.go, quesma/frontend_connectors/search_norace_test.go, quesma/frontend_connectors/search_opensearch_test.go, quesma/frontend_connectors/search_test.go, quesma/frontend_connectors/transformations.go, quesma/processors/es_to_ch_ingest/elasticsearch_to_clickhouse_ingest_processor.go, quesma/processors/es_to_ch_query/elasticsearch_to_clickhouse_query_processor.go, quesma/quesma/dual_write_proxy_v2.go
This PR is about splitting and finally removing the `quesma\quesma\quesma` package and moving the relevant parts to `frontend_connectors`. It is an intermediate step forward. The plan is to further split `frontend_connectors` into smaller, self-contained packages.
=> Moving stuff related to frontend connectors

quesma/ingest/dots.go, quesma/ingest/dots_test.go, quesma/ingest/processor.go, quesma/util/utils.go
This PR solves a bug. When we have documents like 
```
{"foo": {"10": "1"}}
```
Our column mangling mechanism gives two results, `foo__10` and `foo_10`,  depending on the situation (flatten JSON/unprocessed JSON). This is caused by how we process JSONs which is documented in the `processInsertQuery` function.
=> Ingest - column name mangling fix

.github/notice-generator/collect-go-dependencies.sh, .github/notice-generator/collect-manual-notices.sh, .github/notice-generator/go-licence-detector/overrides.ndjson, .github/workflows/generate-notice.yml
1. When `collect-go-dependencies.sh` failed, the "Generate NOTICE.MD" GitHub Actions step didn't fail, because `pipefail` mode wasn't turned on. `shell: bash` fixes that and the step will now correctly fail in such case.
2. `collect-go-dependencies.sh` and `collect-manual-notices.sh` now look for go.mod and NOTICE.MD files recursively (`**` by default doesn't). This catches more things that should be included in `NOTICE.MD`.
=> Small tweaks to NOTICE.MD generator

platform/frontend_connectors/schema_array_transformer.go
Before (Quesma):
After, we give the same results as Elastic:
=> [`sample_ecommerce`] Fix group by SQL for arrays

platform/model/bucket_aggregations/date_histogram.go
I think Elastic has 65536 (2^16), so setting something similar.
After this second PR, all date_histograms start looking exactly the same as from Elastic:
=> [Grafana] Allow adding more than 1000 empty buckets

docs/public/docs/limitations.md, platform/model/README.md, platform/model/bucket_aggregations/geohash_grid.go, platform/model/query_result.go, platform/parsers/elastic_query_dsl/pancake_aggregation_parser_buckets.go, platform/testdata/grafana.go, platform/testdata/unsupported_requests.go
Doesn't support `bounds` parameter, but will warn to logs if someone uses it. Only `precision` is visible in Grafana, so doesn't really matter there. Let's add that in another PR if needed.
=> [Grafana] `geohash_grid`: Support the only new aggregration from Grafana

platform/frontend_connectors/vitess_mysql_connector.go, platform/main.go
It turns out that JUST IMPORTING Vitess messes up logging in the entire application.
Vitess code in its `init()` function (called before our `main`) redirects stderr logging into its own logging implementation (which doesn't print anything for us): https://github.com/vitessio/vitess/blob/41a8d1dd323fb56e9dce88b29c64f9dc87b5a0fe/go/vt/logutil/logutil.go#L17-L18
For now, I just commented out the code that imported (and used) Vitess.
Before the fix, if the config validation failed, it wouldn't print the cause of the failure. After this fix, the cause is now properly printed out:
```
________
\_____  \  __ __   ____   ______ _____ _____
/  / \  \|  |  \_/ __ \ /  ___//     \\__  \
/   \_/.  \  |  /\  ___/ \___ \|  Y Y  \/ __ \_
\_____\ \_/____/  \___  >____  >__|_|  (____  /
\__>           \/ …
```
=> Comment out import of Vitess to fix error logging

platform/ingest/processor.go
1. Let's log full statement which failed, sometimes it's hard to decipher what went wrong just by looking at the error
2. It's not `query`, this part of code handles ingest statements.
=> Log failed ingest statements

.github/workflows/pipeline.yml, .gitmodules, platform/parsers/sql/lexer/dialect_sqlparse/rule_test.go, platform/parsers/sql/lexer/dialects_sqlfluff/ansi/rule_test.go, platform/parsers/sql/lexer/testutils/testdata_loader.go
This PR adds tests of our ports of dialects from sqlparse and sqlfluff.
The test files are extracted SQL queries from the tests of sqlparse and sqlfluff. The expected outputs (tokens) are collected by running the queries through the original lexers of sqlparse and sqlfluff.
By doing this, we get a really good test coverage (>10k SQL queries, many edge case/"strange"/"tricky" SQL queries collected) and we can be almost certain that our implementation behaves identically to the original sqlparse/sqlfluff implementations.
The test files are stored in a separate repo (added to Quesma as a Git submodule), because they are large (~10MB).
=> Add tests of lexer dialects (sqlparse, sqlfluff)

.github/workflows/e2e-tests.yml
After #1313 was merged, we now have a Git submodule for testdata (for lexer). I forgot to update `e2e-test.yml` GitHub Actions workflow to also fetch submodules (other workflows were updated and work correctly).
=> Fix E2E tests failing - fetch submodules

platform/clickhouse/table_discovery.go, platform/clickhouse/table_discovery_test.go
It turned out that we can't handle double-nested arrays in ClickHouse, which caused tables not being visible in Quesma during table discovery.
=> Nested type resolution fixes for `table_discovery.go`

platform/frontend_connectors/schema_transformer.go, platform/parsers/elastic_query_dsl/query_parser.go, platform/testdata/aggregation_requests.go, platform/testdata/kibana_sample_data_flights.go
I need to fix `(( ))` instead of `( )`, but let me do that in another PR. Without it, this PR is very simple and almost certain to be correct.
=> `Match_phrase` accept ints as strings

ci/it/testcases/test_ingest_types.go, platform/ingest/ingest_validator.go, platform/ingest/ingest_validator_test.go, platform/ingest/processor.go, platform/util/maths.go
Before:
dots weren't shown on 2 maps, and we had only nulls in the Clickhouse table (as we somehow get `"35.5"`, not `35.5` in ingest for geopoints, and previous logic put all of that to the attributes, leaving columns as `NULLs`)
After:
=> [Ingest] Accept strings with numeric values (within range) for numeric columns

platform/elasticsearch/mappings.go, platform/frontend_connectors/route_handlers.go, platform/frontend_connectors/schema_transformer.go, platform/functionality/field_capabilities/field_caps.go
This PR:
- fixes few problems with type handing in mappings and field_caps
- extracts `applyFieldMapSyntax` as a separate transformation
This improves field caps experience via mapping
```
PUT foo
{
"mappings": {
"properties": {
"@timestamp": {
"type": "date"
},
"bar": {
"properties": {
"a": {
"type": "text"
},
"c": {
"type": "text"
},
"d": {
"type": "text"
}
}
}
}
}
}
```
=> Dynamic objects fieldcaps fixes #1

platform/clickhouse/schema.go, platform/clickhouse/table_discovery.go, platform/config/config.go, platform/config/config_v2.go, platform/schema/registry.go
This PR adds an automatic map key discovery feature needed for field caps and dashboard creation.
```
CREATE TABLE IF NOT EXISTS "foo"
(
"@timestamp" DateTime64 DEFAULT now64(),
`bar` Map(String, Nullable(String))
)
ENGINE = MergeTree
ORDER BY ("@timestamp");    
insert into foo values ('2020-01-01 00:00:00', {'a': 'b'});
insert into foo values ('2020-01-01 00:00:00', {'c': 'b'});
insert into foo values ('2020-01-01 00:00:00', {'e': 'b'});
```
Feature is hidden behind the global flag:
```
mapFieldsDiscoveringEnabled: true
```
=> Introducing map keys discovering

platform/frontend_connectors/matchers.go, platform/frontend_connectors/route_handlers.go, platform/frontend_connectors/router_v2.go, platform/v2/core/routes/paths.go
Adding a support for CSV export in Kibana.
Kibana CSV report generation uses two steps:
1. Create Point-In-Time  (`:indexPattern/_pit` API) for an index pattern
2. Fetch data via `/_search` API, referencing PIT ID created before
In our case, we're **not** creating any persistent PIT for ClickHouse table - we're simply using that PIT ID as a reference to specific index pattern. So the logic looks like the following:
1. Quesma controls `:indexPattern/_pit` endpoint.
Whenever pit creation is issued and `:indexPattern` is under our control, instead of relaying request to Elasticsearch we respond that PIT has been created and it's ID is `quesma_:indexPattern`.
2. When a request to `/_search` comes to Quesma and it has PIT == `quesma_:indexPattern`, we simply execute query to a table which is …
=> Support Kibana CSV export

platform/functionality/field_capabilities/field_caps.go
Elasticsearch does not emit `.keys()` and `.values()` for maps. Definitely we should not emit `text` type as well. Below `bar` index is handled by elasticsearch.
and `foo` index handled by `quesma` and `clickhouse` after fix.
=> Removing field caps map capabilities to be on par with elasticsearch

platform/clickhouse/type_adapter.go, platform/frontend_connectors/schema_transformer.go, platform/frontend_connectors/schema_transformer_test.go, platform/functionality/field_capabilities/field_caps.go, platform/functionality/field_capabilities/field_caps_test.go, platform/schema/registry.go, platform/schema/registry_test.go, platform/schema/types.go
This PR fixes two issues:
- Ensuring consistency by aligning behavior with Elasticsearch (field_caps inferred types).
- Preventing query failures.
=> ElasticSearch schema consistency fixes, query fixes

platform/clickhouse/schema.go, platform/clickhouse/table_discovery.go, platform/clickhouse/table_discovery_test.go
This PR:
- handles `Map(LowCardinality(String),...)`
- fixes `extractMapValueType`
=> Extending map keys types discovering

platform/frontend_connectors/schema_transformer.go, platform/frontend_connectors/schema_transformer_test.go
a) I think we trimmed `%` from strings a bit too often
b) if trimming `%` from bools or numbers helps, then let's do this as well.
After:
Before:
=> [`flights`, recent regression] Quickfix `__quesma_match` for `bools`

examples/kibana-sample-data/docker-compose.yml, examples/kibana-sample-data/kibana/run.sh, examples/kibana-sample-data/quesma/config/local-dev.yaml
* added `sample_logs`. I checked by running the docker compose myself and the dashboard fully works, so why not do so.
* bumped Clickhouse version to match our local configs
=> Update `examples/` a bit

Dockerfile, platform/backend_connectors/elasticsearch_backend_connector.go, platform/config/config_v2.go, platform/config/elasticsearch_config.go, platform/elasticsearch/client.go, platform/elasticsearch/client_test.go, platform/frontend_connectors/dispatcher.go, platform/telemetry/phone_home.go
In addition to username and password, es/os support client-auth based auth. See [here](https://docs.opensearch.org/docs/latest/security/authentication-backends/client-auth/). This pr wants to support that. 
This change introduces client certificate authentication for Quesm when connecting to Elasticsearch. It does not alter how users authenticate to Quesm.
(this pr is to implement request of this https://github.com/QuesmaOrg/quesma/issues/1394)
=> Support Client certificate authentication for opensearch/elastic search 

platform/frontend_connectors/schema_transformer.go, platform/frontend_connectors/schema_transformer_test.go, platform/testdata/pipeline_aggregation_requests.go
`ILIKE '%%'` has terrible performance, as it semantically means `is not null` we could transform that part of `WHERE` statement for decent speed up.
=> Transform `ILIKE '%%'` to `IS NOT NULL`

platform/parsers/sql/parser/core/helper.go, platform/parsers/sql/parser/core/node.go, platform/parsers/sql/parser/pipe_syntax/enrichments.go, platform/parsers/sql/parser/pipe_syntax/expand_macros.go, platform/parsers/sql/parser/pipe_syntax/group_pipe_syntax.go, platform/parsers/sql/parser/pipe_syntax/transpiler.go, platform/parsers/sql/parser/transforms/group_parenthesis.go
change back to `Add(pipe, ...nodes)` from `Add(&pipe, ...nodes)` which I like more, but idk, maybe you don't.
@avelanarius please look and reject/merge whenever you like, we can wait with this of course.
=> [Transpiler] Small leftovers of refactor

platform/functionality/field_capabilities/field_caps.go, platform/functionality/field_capabilities/field_caps_test.go
Before this PR all sample dashboards load in Kibana 8.11, but one single panel doesn't in newest Kibana 8.17.
After this PR they all load in both of them.
https://github.com/QuesmaOrg/quesma/pull/1321
Draft for a bit, let me inspect a) PR above b) the customer case which was why I also introduced the reverse change a few months ago (we used to have exactly the same version in code as after this PR months ago)
=> [done, needs some testing] Revert `Text/keyword` change?

platform/clickhouse/clickhouse.go
The error message `License checker failed to connect with the database` is very confusing. It was interpreted during a talk with our user as a licensing problem.
This PR:
1. Creates backoff up to a minute, so we don't flood the logs.
2. Reword it too `Failed to connect with the database, can't determine if license is required`.
3. Show underling error.
=> Nicer license checker error message

platform/functionality/resolve/resolve.go
Users should not be able to create a data view that matches the common table.  Querying the common table causes an error. 
This PR filters out our internal common table and index that contains a list of virtual tables.
=> Dont expose internal table/index

ci/it/testcases/test_dual_write_and_common_table.go
PR #1442  changed the way we expose our internal indices. Just forgot to change our integration test. This PR fixed it.
=> Change integration test (should be changed in #1442)

.github/workflows/issues-and-prs.yml
I (and potential outside contributors) don't commit branches to the `QuesmaOrg/quesma` repo, but to personal forks. For such a workflow, the `issues-and-prs.yml` job (Slack notifications for new PRs/issues) didn't work, failing with error:
> Missing input! A token must be provided to use the method decided.
The problem is that the Slack token GitHub secret isn't available for forks - due to security reasons.
However, by changing the type of job from `pull_request` to `pull_request_target`, it changes how GitHub will run the job - it will run it in context of "parent" repo (`QuesmaOrg/quesma`), meaning it has access to the Slack token. 
Some [GitHub documentation](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request …
=> Fix Slack notification not working for PRs from forks

ci/it/configs/quesma-split-time-range.yml.template, ci/it/integration_test.go, ci/it/testcases/test_split_time_range.go
Recently, there was a regression caused by a bug in `splitTimeRangeExt` optimization (see #1454), which splits queries with long time ranges. Our unit/integration tests failed to catch the issue. The reproducer for the issue is to run a `_search` query: sorted by time, over some time range and with a filter.
This PR adds a new integration test. This test runs the reproducing query (`_search` query: sorted by time, over some time range and with a filter), as well as different variations of the query: short/long time range, with/without filter, inclusive/exclusive ends of time range. This should cover the `splitTimeRangeExt` optimization more thoroughly.
There are two types of tests:
- `testTimerangesHandwritten`: handwritten different queries
- `testTimerangesRandom`: randomly generated …
=> Add `split_time_range` integration test

ci/it/configs/quesma-default-schema-override.yml.template, ci/it/integration_test.go, ci/it/testcases/test_default_schema_override.go, platform/config/config.go, platform/config/config_v2_util.go, platform/schema/registry.go
This PR adds a method to apply a schema override to all indices. 
Here is a sample config:
```
"*":
schemaOverrides:
fields:
"message":
type: text
target:
- my-clickhouse-data-source
```
In this case, all indices will have a `message` field with type `text`. It means full-text search will be performed against that field.
=> Default schema overrides

ci/it/configs/quesma-only-common-table.yml.template, ci/it/integration_test.go, ci/it/testcases/test_only_common_table.go, platform/clickhouse/table_discovery.go, platform/frontend_connectors/router_v2.go, platform/persistence/elastic.go, platform/v2/core/routes/paths.go
Quesma relies on `attributes` columns when it calculates the schema change on ingest. Table discovery didn't add these fields to virtual tables.  Therefore, the schema of the index stored in the `common table` becomes immutable within 60 seconds.
=> Lack of schema refresh after new field in common table

platform/ingest/alter_table_test.go, platform/ingest/common_table_test.go, platform/ingest/insert_test.go, platform/ingest/processor.go
`ALTER TABLE` can be expensive in ClickHouse, it's easier and better to combine them. The MVP is to combine adding a new column with adding a comment to it.
=> Combine ALTER TABLE into one

ci/ci.yml, ci/e2e.yml, cmd/experimental/main.go, cmd/experimental/v2_quesma_builder.go, cmd/main.go, cmd/v2_quesma_builder.go, examples/kibana-sample-data/docker-compose.yml, platform/config/config_v2.go, platform/config/config_v2_test.go, platform/config/env2json_test.go
Currently, Quesma is in a restart loop on configuration issues, which is a terrible developer experience. 
Instead of being able to read the error message, it keeps restarting.
My proposal instead is to return exit 0 and not restart. This allows reading messages as well as gives a much faster error in `docker compose up`.
=> Add graceful configuration error

platform/frontend_connectors/schema_transformer.go, platform/testdata/requests.go
This PR fixes keyword field comparison. Quesma was comparing against the `ilike` pattern instead of literal.
=> Fix keyword field comparison

platform/ingest/alter_table_test.go, platform/ingest/processor.go, platform/ingest/processor_test.go
This is small refinement of `GenerateIngestContent` signature to remove redundant argument. We were passing `clickhouse.Table` and `chLib.ChTableConfig` however `Config` can be taken from table
=> Refining GenerateIngestContent signature

platform/ingest/alter_table_test.go, platform/ingest/common_table_test.go, platform/ingest/insert_test.go, platform/ingest/processor.go
This reverts commit 2506adb2b9782a33e61a93af93ae4d8a35893b86.
Combined alter table statements may not always work. 
```
Error executing ingest statement: code: 48, message: For Replicated databases it's not allowed to execute ALTERs of different types (replicated and non replicated) in single query, query: ALTER TABLE "phone_home_logs" ADD COLUMN IF NOT EXISTS "request_id" Nullable(String), COMMENT COLUMN...
```
=> Revert "Combine ALTER TABLE into one (#1463)"

.github/workflows/integration-tests.yml, ci/it/configs/quesma-common-table-and-regular-table.yml.template, ci/it/integration_test.go, ci/it/testcases/test_common_table_and_regular_table.go, http_requests/_mapping.http, platform/common_table/const.go, platform/frontend_connectors/es_responses.go, platform/frontend_connectors/route_handlers.go, platform/frontend_connectors/router_v2.go, platform/functionality/field_capabilities/field_caps.go, platform/processors/es_to_ch_query/elasticsearch_to_clickhouse_query_processor.go, platform/table_resolver/rules.go, platform/table_resolver/table_resolver.go, platform/v2/core/decision.go
This PR fixes getting mappings and fields caps for all indices. 
Details:
- Added * resolve in mapping endpoint,
- Added 'Meta' pipeline in the table resolver. It doesn't check if we are trying to query multiple tables. It's not required while handling metadata (mappings, field caps)
- Added e2e tests.
=> Fix `/*/_mapping` and `/*/_field_caps` handling

.gitignore, .idea/runConfigurations/Debug_Quesma_ITs.xml, ci/it/README.md, ci/it/testcases/base.go, ci/it/testcases/container_utils.go, ci/it/testcases/utils.go
=> Enable running ITs against Quesma with debugger

platform/ingest/processor.go
When users connect Quesma to ClickHouse and would like to work with tables which **are not created by Quesma**, `ALTER` statements doesn't work, unless `attributes_*` columns are present. Therefore we end up with:
1. No `ALTER` executed
2. Extra fields being ignored because we **neither** added the dedicated column **nor** had `attributes_*` column to store it.
In general, we discourage such setup in read/write scenarios - it's always better to have Quesma manage your CH tables so that it controls any required metadata.
In most cases BYOT is used in read-only, ingest-disabled situations. However, there's a simple way to mitigate this limitation:
```
ALTER TABLE test_db.test_table [ON cluster quesma_cluster] ADD COLUMN "attributes_values" Map(String, String)
ALTER TABLE test_db.test_table …
```
=> Comments/docs on "bring your own table" and `ALTER` situation

.idea/runConfigurations/Run_Quesma_Locally.xml
Recent change addition in local debugger run configuration overwritten the "default" run configuration (a.k.a. "play button) in `main.go`.
Therefore, instead of running with default `config.yaml` Quesma ended up loading config from the most recent IT run 🙃
=> Add `Run Quesma Locally` run configuration.

platform/clickhouse/clickhouse_schema.go, platform/database_common/schema.go, platform/database_common/schema_test.go, platform/database_common/table.go, platform/database_common/table_discovery.go, platform/database_common/table_discovery_test.go, platform/doris/doris_schema.go, platform/ingest/processor.go
=> Adapt doris schema type

platform/model/bucket_aggregations/date_histogram.go
Since the data is converted into string type in the data reading of doris, we need to process the string type specifically here.
Related PR: https://github.com/QuesmaOrg/quesma/blob/main/platform/database_common/quesma_communicator.go#L228
=> Adapt to string type time data

platform/frontend_connectors/physical_functions.go, platform/frontend_connectors/schema_transformer.go, platform/frontend_connectors/schema_transformer_test.go, platform/frontend_connectors/search_opensearch_test.go, platform/frontend_connectors/search_test.go, platform/frontend_connectors/terms_enum_test.go, platform/model/constants.go, platform/model/where_visitor.go, platform/parsers/elastic_query_dsl/aggregation_parser_test.go, platform/parsers/elastic_query_dsl/dates.go, platform/parsers/elastic_query_dsl/pancake_sql_query_generation_test.go, platform/parsers/elastic_query_dsl/query_parser_range_test.go, platform/testdata/aggregation_requests.go, platform/testdata/aggregation_requests_2.go, platform/testdata/clients/clover.go, platform/testdata/dates.go, platform/testdata/kibana-visualize/aggregation_requests.go, platform/testdata/kibana-visualize/pipeline_aggregation_requests.go, platform/testdata/kibana_sample_data_ecommerce.go, platform/testdata/kibana_sample_data_flights.go, platform/testdata/kibana_sample_data_logs.go, platform/testdata/opensearch-visualize/aggregation_requests.go, platform/testdata/opensearch-visualize/pipeline_aggregation_requests.go, platform/testdata/opensearch_requests.go, platform/testdata/request_after_transformations.go, platform/testdata/requests.go, platform/util/utils.go
This PR introduces an abstract logical `FromUnixTimeFunction` and `FromUnixTimeFunction64mili` functions to be used at the parsing level, and adds a extend DateTimeFunction transformation that lowers it to a backend-specific implementation.
=> Introducing logical fromUnixTime func
